import Link from 'next/link'
import TaxpayerSidebar from '@/app/components/TaxpayerSidebar'
import FraudContextFields from '@/app/components/FraudContextFields'
import HmrcAttemptStatus from '@/app/components/HmrcAttemptStatus'
import { supabaseAdmin } from '@/lib/supabase-admin'
import { latestHmrcAttempt, latestHmrcResponse } from '@/lib/hmrc-response-audit'

export const dynamic='force-dynamic'

export default async function OtherIncomePage({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<Record<string,string|undefined>>}){
 const {id}=await params;const qs=await searchParams;const db=supabaseAdmin();const {data:obligations}=await db.from('hmrc_obligations').select('period_start').eq('taxpayer_id',id).gte('period_start','2025-04-06')
 const years=Array.from(new Set((obligations||[]).map((o:any)=>{const d=String(o.period_start);const y=Number(d.slice(0,4));return `${y}-${String(y+1).slice(-2)}`}))).sort().reverse();const selected=qs.taxYear&&years.includes(qs.taxYear)?qs.taxYear:(years[0]||'2026-27');const stored=await latestHmrcResponse(db,{taxpayerId:id,taxYear:selected,eventType:'other_income_retrieval'});const latestAttempt=await latestHmrcAttempt(db,{taxpayerId:id,taxYear:selected,eventType:'other_income_retrieval'});const result=stored?.response_summary||stored?.response_payload||null;const is2026On=Number(selected.slice(0,4))>=2026;const hmrcOtherIncomeAvailable=!is2026On||process.env.HMRC_OTHER_INCOME_V3_ENABLED==='true'
 const categories=[['propertyIncomeDistributions','Property income distributions'],['personalInsuranceBenefits','Personal insurance benefits'],['incomeFromUnauthorisedUnitTrust','Unauthorised unit trust income'],['profitsFromCertificateOfDeposit','Certificate of deposit profits'],['nonCashBenefitsFromFormerEmployer','Non cash benefits from former employer'],['authorisedPaymentsFromOverseasPensionScheme','Overseas pension scheme payments'],['taxableAnnualPayments','Taxable annual payments'],['miscellaneousIncome','Miscellaneous income']]
 return <div className="shell"><TaxpayerSidebar taxpayerId={id} active="other-income"/><main className="main">
  <div className="top"><div><h1 className="pageTitle">Other Self Assessment Income</h1><p className="muted">Review and update HMRC Other Income categories before the end of year calculation and declaration.</p></div><span className="badge">{selected}</span></div>
  {qs.error&&<div className="status statusError"><strong>HMRC needs attention.</strong><div>{qs.error}</div>{qs.correlationId&&<div className="muted">Correlation ID: {qs.correlationId}</div>}</div>}
  {qs.saved&&<div className="status"><strong>Other Income saved to HMRC.</strong>{qs.correlationId&&<div className="muted">Correlation ID: {qs.correlationId}</div>}</div>}
  {qs.deleted&&<div className="status"><strong>Other Income deleted from HMRC.</strong>{qs.correlationId&&<div className="muted">Correlation ID: {qs.correlationId}</div>}</div>}
  {!hmrcOtherIncomeAvailable&&<div className="status statusError"><strong>HMRC Other Income actions are temporarily unavailable for {selected}.</strong><div>You can still prepare and review the figures in MTD Lab. Retrieve, save and delete actions remain locked until the HMRC 2026/27 Other Income API version is enabled.</div></div>}
  <section className="panel"><div className="sectionHead"><div><h2>HMRC other income</h2><p className="muted">Retrieve the taxpayer's current Other Income record from HMRC for the selected tax year.</p></div><form method="get"><select className="selectField" name="taxYear" defaultValue={selected}>{years.length?years.map(y=><option key={y} value={y}>{y}</option>):<option value={selected}>{selected}</option>}</select><button className="btn btnSmall" type="submit">Change year</button></form></div>{hmrcOtherIncomeAvailable?<Link className="btn" href={`/api/hmrc/other-income/retrieve?taxpayerId=${encodeURIComponent(id)}&taxYear=${encodeURIComponent(selected)}`}>Retrieve other income from HMRC</Link>:<button className="btn" type="button" disabled>HMRC retrieval unavailable for {selected}</button>}</section>
  {!qs.error&&<HmrcAttemptStatus attempt={latestAttempt} label="Other income"/>}
  {qs.retrieved&&result&&<section className="panel" style={{marginTop:16}}><div className="sectionHead"><div><h2>HMRC record</h2><p className="muted">Retrieved directly from HMRC.</p></div>{qs.correlationId&&<span className="badge">Correlation {qs.correlationId}</span>}</div><details open><summary>View other income response</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(result,null,2)}</pre></details></section>}
  <section className="panel" style={{marginTop:16}}><h2>Create or amend Other Income</h2><p className="muted">The available fields follow the HMRC schema for {selected}. Fields that no longer belong to the 2026/27 onward schema are not shown.</p>
   <form method="post" action="/api/hmrc/other-income/amend"><input type="hidden" name="taxpayerId" value={id}/><input type="hidden" name="taxYear" value={selected}/><FraudContextFields/>
    <div className="cards">
     <div className="card"><span className="eyebrow">Post cessation receipt</span><label>Amount<input className="inputField" name="postCessationAmount" type="number" min="0" step="0.01"/></label><label>Tax year to be taxed<input className="inputField" name="postCessationTaxYear" defaultValue={selected}/></label><label>Business name<input className="inputField" name="postBusinessName"/></label><label>Customer reference<input className="inputField" name="postCustomerReference"/></label><label>Date business ceased<input className="inputField" name="dateBusinessCeased" type="date"/></label><label>Business description<input className="inputField" name="businessDescription"/></label><label>Income source<input className="inputField" name="postIncomeSource"/></label></div>
     {!is2026On&&<div className="card"><span className="eyebrow">Business receipt taxed in another year</span><label>Gross amount<input className="inputField" name="businessReceiptGross" type="number" min="0" step="0.01"/></label><label>Tax year<input className="inputField" name="businessReceiptTaxYear" placeholder={selected}/></label></div>}
     <div className="card"><span className="eyebrow">Overseas income and gains</span><label>Gain amount<input className="inputField" name="overseasGainAmount" type="number" min="0" step="0.01"/></label></div>
     <div className="card"><span className="eyebrow">Omitted foreign income</span><label>Amount<input className="inputField" name="omittedForeignIncomeAmount" type="number" min="0" step="0.01"/></label></div>
    </div>
    {is2026On&&<><h3 style={{marginTop:20}}>Foreign and additional income, 2026/27 onwards</h3><div className="cards">
      <div className="card"><span className="eyebrow">Income received whilst abroad</span><label>Country code<input className="inputField" name="abroadCountryCode" maxLength={3} placeholder="FRA"/></label><label>Amount before tax<input className="inputField" name="abroadAmountBeforeTax" type="number" min="0" step="0.01"/></label><label>Tax taken off<input className="inputField" name="abroadTaxTakenOff" type="number" min="0" step="0.01"/></label><label>Special withholding tax<input className="inputField" name="abroadSpecialWithholdingTax" type="number" min="0" step="0.01"/></label><label>Taxable amount<input className="inputField" name="abroadTaxableAmount" type="number" min="0" step="0.01"/></label><label>Residential finance cost<input className="inputField" name="abroadResidentialFinancialCost" type="number" min="0" step="0.01"/></label><label>Brought forward residential finance cost<input className="inputField" name="abroadBroughtForwardResidentialFinancialCost" type="number" min="0" step="0.01"/></label><label style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" name="abroadForeignTaxCreditRelief" value="yes"/>Foreign Tax Credit Relief claimed</label></div>
      <div className="card"><span className="eyebrow">Chargeable foreign benefits and gifts</span><label>Transaction benefit<input className="inputField" name="transactionBenefit" type="number" min="0" step="0.01"/></label><label>Protected foreign income source benefit<input className="inputField" name="protectedForeignIncomeSourceBenefit" type="number" min="0" step="0.01"/></label><label>Protected foreign income onward gift<input className="inputField" name="protectedForeignIncomeOnwardGift" type="number" min="0" step="0.01"/></label><label>Benefit received as settler<input className="inputField" name="benefitReceivedAsASettler" type="number" min="0" step="0.01"/></label><label>Onward gift received as settler<input className="inputField" name="onwardGiftReceivedAsASettler" type="number" min="0" step="0.01"/></label></div>
      <div className="card"><span className="eyebrow">Benefit from pre owned assets</span><label>Type of asset<input className="inputField" name="preOwnedAssetType" placeholder="Residential property"/></label><label>Amount of benefit<input className="inputField" name="preOwnedAssetAmount" type="number" min="0" step="0.01"/></label></div>
      <div className="card"><span className="eyebrow">Additional taxable income</span><label>Category<select className="selectField" name="additionalIncomeCategory" defaultValue=""><option value="">Choose category</option>{categories.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Amount before tax<input className="inputField" name="additionalAmountBeforeTax" type="number" min="0" step="0.01"/></label><label>Allowable expenses<input className="inputField" name="additionalAllowableExpenses" type="number" min="0" step="0.01"/></label><label>Tax deducted<input className="inputField" name="additionalTaxDeducted" type="number" min="0" step="0.01"/></label><label>Losses brought forward<input className="inputField" name="additionalLossesBroughtForward" type="number" min="0" step="0.01"/></label><label>Carry forward losses<input className="inputField" name="additionalCarryForwardLosses" type="number" min="0" step="0.01"/></label></div>
    </div></>}
    <button className="btn" type="submit" style={{marginTop:12}} disabled={!hmrcOtherIncomeAvailable}>{hmrcOtherIncomeAvailable?'Save Other Income to HMRC':`HMRC save unavailable for ${selected}`}</button>
   </form>
  </section>
  <section className="panel" style={{marginTop:16}}><h2>Delete HMRC Other Income record</h2><p className="muted">HMRC's delete operation removes the Other Income record for the selected tax year. Use this only when the record should no longer exist.</p><form method="post" action="/api/hmrc/other-income/delete"><input type="hidden" name="taxpayerId" value={id}/><input type="hidden" name="taxYear" value={selected}/><FraudContextFields/><label style={{display:'flex',gap:8,alignItems:'center',margin:'12px 0'}}><input type="checkbox" name="confirmDelete" value="yes" disabled={!hmrcOtherIncomeAvailable}/>I confirm that the Other Income record for {selected} should be deleted from HMRC.</label><button className="btn btnSmall" type="submit" disabled={!hmrcOtherIncomeAvailable}>{hmrcOtherIncomeAvailable?'Delete Other Income from HMRC':`HMRC delete unavailable for ${selected}`}</button></form></section>
  <section className="panel" style={{marginTop:16}}><h2>Year end control</h2><p className="muted">For 2026/27 onwards MTD Lab exposes the newer HMRC foreign, pre owned asset and additional income structures for preparation. HMRC actions remain locked until the compatible API version is enabled.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Link className="btn btnSmall" href={`/taxpayers/${id}/end-of-year?taxYear=${encodeURIComponent(selected)}`}>Back to End of Year</Link><Link className="btn btnSmall" href={`/taxpayers/${id}/end-of-year/reliefs?taxYear=${encodeURIComponent(selected)}`}>Reliefs and Deductions</Link></div></section>
 </main></div>
}