import Link from 'next/link'
import TaxpayerSidebar from '@/app/components/TaxpayerSidebar'
import FraudContextFields from '@/app/components/FraudContextFields'
import { supabaseAdmin } from '@/lib/supabase-admin'

export const dynamic='force-dynamic'
function decode(value?:string){try{return value?JSON.parse(Buffer.from(value,'base64url').toString('utf8')):null}catch{return null}}

export default async function OtherIncomePage({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<Record<string,string|undefined>>}){
 const {id}=await params;const qs=await searchParams;const db=supabaseAdmin();const {data:obligations}=await db.from('hmrc_obligations').select('period_start').eq('taxpayer_id',id).gte('period_start','2025-04-06')
 const years=Array.from(new Set((obligations||[]).map((o:any)=>{const d=String(o.period_start);const y=Number(d.slice(0,4));return `${y}-${String(y+1).slice(-2)}`}))).sort().reverse();const selected=qs.taxYear&&years.includes(qs.taxYear)?qs.taxYear:(years[0]||'2026-27');const result=decode(qs.result)
 return <div className="shell"><TaxpayerSidebar taxpayerId={id} active="other-income"/><main className="main">
  <div className="top"><div><h1 className="pageTitle">Other Self Assessment Income</h1><p className="muted">Review and update supported HMRC Other Income categories before the end of year calculation and declaration.</p></div><span className="badge">{selected}</span></div>
  {qs.error&&<div className="status statusError"><strong>HMRC needs attention.</strong><div>{qs.error}</div>{qs.correlationId&&<div className="muted">Correlation ID: {qs.correlationId}</div>}</div>}
  {qs.saved&&<div className="status"><strong>Other Income saved to HMRC.</strong>{qs.correlationId&&<div className="muted">Correlation ID: {qs.correlationId}</div>}</div>}
  {qs.deleted&&<div className="status"><strong>Other Income deleted from HMRC.</strong>{qs.correlationId&&<div className="muted">Correlation ID: {qs.correlationId}</div>}</div>}
  <section className="panel"><div className="sectionHead"><div><h2>HMRC other income</h2><p className="muted">Retrieve the taxpayer's current Other Income record from HMRC for the selected tax year.</p></div><form method="get"><select className="selectField" name="taxYear" defaultValue={selected}>{years.length?years.map(y=><option key={y} value={y}>{y}</option>):<option value={selected}>{selected}</option>}</select><button className="btn btnSmall" type="submit">Change year</button></form></div><Link className="btn" href={`/api/hmrc/other-income/retrieve?taxpayerId=${encodeURIComponent(id)}&taxYear=${encodeURIComponent(selected)}`}>Retrieve other income from HMRC</Link></section>
  {qs.retrieved&&result&&<section className="panel" style={{marginTop:16}}><div className="sectionHead"><div><h2>HMRC record</h2><p className="muted">Retrieved directly from HMRC.</p></div>{qs.correlationId&&<span className="badge">Correlation {qs.correlationId}</span>}</div><details open><summary>View other income response</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(result,null,2)}</pre></details></section>}
  <section className="panel" style={{marginTop:16}}><h2>Create or amend supported Other Income</h2><p className="muted">This first writable stage covers HMRC categories whose required fields can be validated clearly. More complex foreign income categories will be added separately.</p>
   <form method="post" action="/api/hmrc/other-income/amend"><input type="hidden" name="taxpayerId" value={id}/><input type="hidden" name="taxYear" value={selected}/><FraudContextFields/>
    <div className="cards">
     <div className="card"><span className="eyebrow">Post cessation receipt</span><label>Amount<input className="inputField" name="postCessationAmount" type="number" min="0" step="0.01"/></label><label>Tax year to be taxed<input className="inputField" name="postCessationTaxYear" placeholder="2026-27"/></label><label>Business name<input className="inputField" name="postBusinessName"/></label><label>Customer reference<input className="inputField" name="postCustomerReference"/></label><label>Date business ceased<input className="inputField" name="dateBusinessCeased" type="date"/></label><label>Business description<input className="inputField" name="businessDescription"/></label><label>Income source<input className="inputField" name="postIncomeSource"/></label></div>
     <div className="card"><span className="eyebrow">Business receipt taxed in another year</span><label>Gross amount<input className="inputField" name="businessReceiptGross" type="number" min="0" step="0.01"/></label><label>Tax year<input className="inputField" name="businessReceiptTaxYear" placeholder="2026-27"/></label></div>
     <div className="card"><span className="eyebrow">Overseas income and gains</span><label>Gain amount<input className="inputField" name="overseasGainAmount" type="number" min="0" step="0.01"/></label></div>
     <div className="card"><span className="eyebrow">Omitted foreign income</span><label>Amount<input className="inputField" name="omittedForeignIncomeAmount" type="number" min="0" step="0.01"/></label></div>
    </div><button className="btn" type="submit" style={{marginTop:12}}>Save Other Income to HMRC</button>
   </form>
  </section>
  <section className="panel" style={{marginTop:16}}><h2>Delete HMRC Other Income record</h2><p className="muted">HMRC's delete operation removes the Other Income record for the selected tax year. Use this only when the record should no longer exist.</p><form method="post" action="/api/hmrc/other-income/delete"><input type="hidden" name="taxpayerId" value={id}/><input type="hidden" name="taxYear" value={selected}/><FraudContextFields/><label style={{display:'flex',gap:8,alignItems:'center',margin:'12px 0'}}><input type="checkbox" name="confirmDelete" value="yes"/>I confirm that the Other Income record for {selected} should be deleted from HMRC.</label><button className="btn btnSmall" type="submit">Delete Other Income from HMRC</button></form></section>
  <section className="panel" style={{marginTop:16}}><h2>Year end control</h2><p className="muted">The remaining foreign income and additional income categories have more detailed HMRC validation. They will be exposed as separate forms rather than compressed into one generic box.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Link className="btn btnSmall" href={`/taxpayers/${id}/end-of-year?taxYear=${encodeURIComponent(selected)}`}>Back to End of Year</Link><Link className="btn btnSmall" href={`/taxpayers/${id}/end-of-year/reliefs?taxYear=${encodeURIComponent(selected)}`}>Reliefs and Deductions</Link></div></section>
 </main></div>
}
