import Link from 'next/link'
import TaxpayerSidebar from '@/app/components/TaxpayerSidebar'
import { supabaseAdmin } from '@/lib/supabase-admin'
import { listMtdIncomeSources, type MtdIncomeSourceRecord } from '@/lib/mtd-income-sources-server'
import type { MtdIncomeSourceType } from '@/lib/mtd-income-source'
import { currentWorkspace } from '@/lib/workspace'

export const dynamic='force-dynamic'
function decodeIssues(value?:string){try{return value?JSON.parse(Buffer.from(value,'base64url').toString('utf8')):[]}catch{return []}}

const laneMeta:Record<MtdIncomeSourceType,{label:string;subtitle:string;description:string}>={
 'self-employment':{label:'Self Assessment',subtitle:'Self Employment',description:'Business income and expense records for Self Assessment quarterly updates.'},
 'uk-property':{label:'UK Property',subtitle:'UK Property',description:'UK property income and allowable expense records.'},
 'foreign-property':{label:'Foreign Property',subtitle:'Foreign Property',description:'Foreign property income and allowable expense records.'}
}

export default async function Page({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<Record<string,string|undefined>>}){
 const {id}=await params
 const q=await searchParams
 const importIssues:any[]=decodeIssues(q.importIssues)
 const db=supabaseAdmin()
 const workspace=await currentWorkspace()
 const firmId=workspace?.firmId||''
 let sources:MtdIncomeSourceRecord[]
 try{sources=firmId?await listMtdIncomeSources(db,id,firmId):[]}catch{sources=[]}
 const canonicalRequestedType=q.sourceType==='property'?'uk-property':q.sourceType
 const requestedType=(['self-employment','uk-property','foreign-property'].includes(String(canonicalRequestedType))?canonicalRequestedType:'self-employment') as MtdIncomeSourceType
 const availableTypes=(['self-employment','uk-property','foreign-property'] as MtdIncomeSourceType[]).filter(sourceType=>sources.some(source=>source.sourceType===sourceType))
 const requestedSource=sources.find(source=>source.businessId===q.businessId)
 const selectedType=requestedSource?.sourceType||(sources.some(source=>source.sourceType===requestedType)?requestedType:sources[0]?.sourceType||requestedType)
 const laneSources=sources.filter(source=>source.sourceType===selectedType)
 const selectedSource=requestedSource?.sourceType===selectedType?requestedSource:laneSources[0]
 const recordType=['income','expense'].includes(String(q.recordType))?String(q.recordType):'all'
 let query=db.from('mtd_digital_records').select('*').eq('taxpayer_id',id).eq('firm_id',firmId).order('transaction_date',{ascending:false}).limit(250)
 if(selectedSource)query=query.eq('business_id',selectedSource.businessId)
 else query=query.eq('business_id','__no_income_source__')
 if(recordType!=='all')query=query.eq('record_type',recordType)
 const {data:records}=await query
 const rows=records||[]
 const income=rows.filter((r:any)=>r.record_type==='income').reduce((sum:number,row:any)=>sum+Number(row.amount||0),0)
 const expenses=rows.filter((r:any)=>r.record_type==='expense').reduce((sum:number,row:any)=>sum+Number(row.amount||0),0)
 const meta=laneMeta[selectedType]
 const sourceQuery=selectedSource?`sourceType=${encodeURIComponent(selectedType)}&businessId=${encodeURIComponent(selectedSource.businessId)}`:`sourceType=${encodeURIComponent(selectedType)}`
 return <div className="shell"><TaxpayerSidebar taxpayerId={id} active="digital-records" sourceTypes={availableTypes}/><main className="main">
  <div className="top"><div><h1 className="pageTitle">Digital Records</h1><p className="muted">Keep separate digital records for each MTD Income Tax income source.</p></div><a className="btn btnSmall" href={`/api/digital-records/template?${sourceQuery}`}>Download {meta.label} CSV template</a></div>
  <div className="cards">{availableTypes.length?availableTypes.map(laneType=>{const lane=laneMeta[laneType];const laneItems=sources.filter(source=>source.sourceType===laneType);return <div className="card" key={laneType}><span className="eyebrow">{lane.label}</span><strong className="dateValue">{lane.subtitle}</strong><p className="muted">{lane.description}</p><Link className="btn btnSmall" href={`/taxpayers/${id}/digital-records?sourceType=${laneType}&businessId=${encodeURIComponent(laneItems[0].businessId)}`}>Open records</Link></div>}):<div className="card"><span className="eyebrow">Income sources</span><strong>No HMRC source available</strong><p className="muted">Synchronise HMRC before adding digital records.</p></div>}</div>
  {q.saved&&<div className="status"><strong>Digital record saved.</strong></div>}
  {q.deleted&&<div className="status"><strong>Digital record corrected.</strong><div className="muted">The removed record will no longer be included in cumulative quarterly totals.</div></div>}
  {q.evidenceUploaded&&<div className="status"><strong>Supporting document uploaded securely.</strong></div>}
  {q.evidenceDeleted&&<div className="status"><strong>Supporting document removed.</strong></div>}
  {q.imported!==undefined&&<div className="status"><strong>CSV import complete.</strong><div className="muted">Imported {q.imported} record(s). Skipped {q.skipped||'0'} invalid, duplicate, or mismatched source row(s).</div></div>}
  {importIssues.length>0&&<div className="status statusError"><strong>Rows requiring correction</strong><div className="muted" style={{marginTop:6}}>Correct these rows in the CSV and import it again. Valid non-duplicate rows were imported.</div><ul>{importIssues.map((issue:any,index:number)=><li key={`${issue.row}-${index}`}><strong>Row {issue.row}:</strong> {issue.message}</li>)}</ul>{Number(q.skipped||0)>importIssues.length&&<div className="muted">Only the first {importIssues.length} issues are shown.</div>}</div>}
  {q.error&&<div className="status statusError">{q.error}</div>}
  <section className="panel"><div className="sectionHead"><div><h2>{meta.label} Digital Records</h2><p className="muted">{selectedSource?.businessName||meta.subtitle}{selectedSource?.fallback?' · Identified from HMRC obligations':''}</p><div className="mono muted">{selectedSource?.businessId||'No matching HMRC income source'}</div></div>{laneSources.length>1&&<div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{laneSources.map(source=><Link className="btn btnSmall" key={source.businessId} href={`/taxpayers/${id}/digital-records?sourceType=${selectedType}&businessId=${encodeURIComponent(source.businessId)}`}>{source.businessName||source.businessId}</Link>)}</div>}</div>
   <h3>Add income or expense</h3><form method="post" action="/api/digital-records/save" className="formGrid"><input type="hidden" name="taxpayerId" value={id}/><input type="hidden" name="businessId" value={selectedSource?.businessId||''}/><input type="hidden" name="sourceType" value={selectedType}/><label>Income source<input className="input" value={selectedSource?.businessName||selectedSource?.businessId||'No income source'} readOnly/></label><label>Date<input className="input" name="transactionDate" type="date" required/></label><label>Type<select className="selectField" name="recordType" required><option value="income">Income</option><option value="expense">Expense</option></select></label><label>MTD category<input className="input" name="category" required placeholder="Income or expense category"/></label><label>Amount (£)<input className="input" name="amount" type="number" min="0" step="0.01" required/></label><label>Description<input className="input" name="description" placeholder="Optional description"/></label><label>Receipt or invoice reference<input className="input" name="documentReference" placeholder="Optional supporting evidence reference"/></label><button className="btn" type="submit" disabled={!selectedSource}>Save {meta.label} record</button></form>
  </section>
  <section className="panel" style={{marginTop:16}}><div className="sectionHead"><div><h2>Import {meta.label} records</h2><p className="muted">Upload the CSV template for this exact HMRC income source. Rows for other sources are skipped.</p></div><a className="btn btnSmall" href={`/api/digital-records/template?${sourceQuery}`}>Download CSV template</a></div><form method="post" action="/api/digital-records/import" encType="multipart/form-data"><input type="hidden" name="taxpayerId" value={id}/><input type="hidden" name="businessId" value={selectedSource?.businessId||''}/><input type="hidden" name="sourceType" value={selectedType}/><input className="input" type="file" name="file" accept=".csv,text/csv" required/><button className="btn" type="submit" style={{marginTop:10}} disabled={!selectedSource}>Validate and import {meta.label} CSV</button></form></section>
  <section className="panel" style={{marginTop:16}}><div className="cards"><div className="card"><span className="eyebrow">Records</span><strong>{rows.length}</strong></div><div className="card"><span className="eyebrow">Income</span><strong>£{income.toFixed(2)}</strong></div><div className="card"><span className="eyebrow">Expenses</span><strong>£{expenses.toFixed(2)}</strong></div><div className="card"><span className="eyebrow">Net</span><strong>£{(income-expenses).toFixed(2)}</strong></div></div><div style={{display:'flex',gap:8,marginTop:12,flexWrap:'wrap'}}><Link className="btn btnSmall" href={`/taxpayers/${id}/quarterly?businessId=${encodeURIComponent(selectedSource?.businessId||'')}&sourceType=${encodeURIComponent(selectedType)}`}>Use records for quarterly updates</Link></div></section>
  <section className="panel" style={{marginTop:16}}><div className="sectionHead"><div><h2>Recent {meta.label} records</h2><p className="muted">Filter this income source by record type. Receipts and invoices are stored privately and every change is audited.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{['all','income','expense'].map(filter=><Link key={filter} className="btn btnSmall" href={`/taxpayers/${id}/digital-records?${sourceQuery}&recordType=${filter}`}>{filter==='all'?'All records':filter==='income'?'Income only':'Expenses only'}</Link>)}</div></div><div className="tableWrap"><table><thead><tr><th>Date</th><th>Income source</th><th>Type</th><th>Category</th><th>Description</th><th>Evidence</th><th>Amount</th><th>Correction</th></tr></thead><tbody>{rows.length?rows.map((row:any)=><tr key={row.id}><td>{row.transaction_date}</td><td><strong>{meta.label}</strong><div className="mono muted">{row.business_id}</div></td><td>{row.record_type}</td><td>{row.category}</td><td>{row.description||'None'}</td><td><div>{row.source_reference||'No reference'}</div>{row.document_url?<><a className="btn btnSmall" href={`/api/digital-records/evidence/download?taxpayerId=${encodeURIComponent(id)}&recordId=${encodeURIComponent(row.id)}`}>Download {row.document_name||'document'}</a><form method="post" action="/api/digital-records/evidence/delete" style={{marginTop:6}}><input type="hidden" name="taxpayerId" value={id}/><input type="hidden" name="recordId" value={row.id}/><input type="hidden" name="businessId" value={selectedSource?.businessId||''}/><input type="hidden" name="sourceType" value={selectedType}/><button className="btn btnSmall btnDangerSecondary" type="submit">Remove document</button></form></>:<form method="post" action="/api/digital-records/evidence/upload" encType="multipart/form-data" style={{marginTop:6,minWidth:220}}><input type="hidden" name="taxpayerId" value={id}/><input type="hidden" name="recordId" value={row.id}/><input type="hidden" name="businessId" value={selectedSource?.businessId||''}/><input type="hidden" name="sourceType" value={selectedType}/><input className="input" type="file" name="file" accept=".pdf,.jpg,.jpeg,.png,.webp,application/pdf,image/jpeg,image/png,image/webp" required/><button className="btn btnSmall" type="submit" style={{marginTop:5}}>Upload evidence</button></form>}</td><td>£{Number(row.amount||0).toFixed(2)}</td><td><form method="post" action="/api/digital-records/delete"><input type="hidden" name="taxpayerId" value={id}/><input type="hidden" name="recordId" value={row.id}/><input type="hidden" name="businessId" value={selectedSource?.businessId||''}/><input type="hidden" name="sourceType" value={selectedType}/><button className="btn btnSmall" type="submit">Remove incorrect record</button></form></td></tr>):<tr><td colSpan={8} className="empty">No {recordType==='all'?'':recordType+' '}digital records are available for this income source.</td></tr>}</tbody></table></div></section>
 </main></div>
}
