import Link from 'next/link'
import FraudContextFields from './FraudContextFields'
import { verifyReviewPayload } from '@/lib/review-token'
import TaxpayerSidebar from '@/app/components/TaxpayerSidebar'
import { supabaseAdmin } from '@/lib/supabase-admin'

function gbp(n:number){return new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(n||0)}
function fmtDate(value?:string){if(!value)return 'Not available';const d=new Date(`${value}T00:00:00`);return Number.isNaN(d.getTime())?value:d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}
function decodeErrors(value?:string){try{return value?JSON.parse(Buffer.from(value,'base64url').toString('utf8')):[]}catch{return []}}

const selfRows=[['turnover','Turnover'],['otherIncome','Other income'],['taxTakenOff','Tax taken off trading income'],['costOfGoods','Cost of goods sold'],['cisPayments','CIS payments to subcontractors'],['staffCosts','Wages and staff costs'],['travelCosts','Car, van and travel expenses'],['premisesCosts','Premises running costs'],['repairsMaintenance','Repairs and maintenance'],['officeCosts','Office costs'],['advertisingCosts','Advertising costs'],['businessEntertainment','Business entertainment'],['interestLoans','Interest on loans'],['financialCharges','Financial charges'],['badDebts','Irrecoverable debts'],['professionalFees','Professional fees'],['depreciation','Depreciation'],['otherExpenses','Other expenses']]
const ukPropertyRows=[['rents','Total rent'],['leasePremiums','Premiums for grant of a lease'],['reversePremiums','Reverse premiums and inducements'],['otherIncome','Other property income'],['premisesCosts','Rent, rates, insurance and ground rents'],['repairsMaintenance','Property repairs and maintenance'],['financialCosts','Property finance costs'],['professionalFees','Legal, management and professional fees'],['costOfServices','Costs of services provided'],['travelCosts','Travel expenses'],['otherExpenses','Other allowable property expenses']]
const foreignPropertyRows=[['rents','Total rents and other receipts'],['leasePremiums','Premiums for grant of a lease'],['propertyExpenses','Allowable property expenses']]

export default async function ReviewPage({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<Record<string,string|undefined>>}){
 const {id}=await params;const qs=await searchParams;const token=String(qs.data||'');const p:any=verifyReviewPayload(token)
 if(!p||p.taxpayerId!==id)return <main className="main"><h1>Quarterly update</h1><p>Review data is missing, invalid or has been altered.</p><Link className="btn" href={`/taxpayers/${id}/submissions`}>Return to Submission Centre</Link></main>
 const {data:agentRows}=await supabaseAdmin().from('mtd_agent_authorisations').select('agent_id,expires_at,mtd_agents(agent_name,organisation_name,hmrc_arn,status)').eq('taxpayer_id',id).eq('status','authorised').eq('can_submit_quarterly',true)
 const agents=(agentRows||[]).filter((r:any)=>(!r.expires_at||new Date(r.expires_at).getTime()>Date.now())&&(!r.mtd_agents?.status||r.mtd_agents.status==='active'))
 const sourceType=String(p.incomeSourceType||p.filingType||'self-employment')
 const foreign=sourceType==='foreign-property';const ukProperty=sourceType==='uk-property'||(!p.incomeSourceType&&p.filingType==='property');const property=foreign||ukProperty
 const sourceLabel=foreign?'Foreign Property':ukProperty?'UK Property':'Self Employment'
 const rows=foreign?foreignPropertyRows:ukProperty?ukPropertyRows:selfRows
 const incomeKeys=foreign?['rents','leasePremiums']:ukProperty?['rents','leasePremiums','reversePremiums','otherIncome']:['turnover','otherIncome']
 const expenseKeys=foreign?['propertyExpenses']:ukProperty?['premisesCosts','repairsMaintenance','financialCosts','professionalFees','costOfServices','travelCosts','otherExpenses']:['costOfGoods','cisPayments','staffCosts','travelCosts','premisesCosts','repairsMaintenance','officeCosts','advertisingCosts','businessEntertainment','interestLoans','financialCharges','badDebts','professionalFees','depreciation','otherExpenses']
 const income=incomeKeys.reduce((s,k)=>s+Number(p[k]||0),0);const expenses=expenseKeys.reduce((s,k)=>s+Number(p[k]||0),0);const missing=String(qs.missing||'').split(',').filter(Boolean)
 const hmrcErrors:any[]=decodeErrors(qs.hmrcErrors)
 const editData={...p};delete editData.preparedAt
 const imported=Buffer.from(JSON.stringify(editData),'utf8').toString('base64url')
 const editHref=`/taxpayers/${id}/submissions?type=${encodeURIComponent(sourceType)}&imported=${encodeURIComponent(imported)}&businessId=${encodeURIComponent(p.businessId||'')}&periodStart=${encodeURIComponent(p.periodStart||'')}&periodEnd=${encodeURIComponent(p.periodEnd||'')}`
 return <div className="shell"><TaxpayerSidebar taxpayerId={id} active="submissions"/><main className="main"><div className="top"><div><h1 className="pageTitle">Review {sourceLabel} update</h1><p className="muted">Check these cumulative figures before HMRC submission.</p></div><span className="badge">{qs.submitted?'Submitted':'Not submitted'}</span></div>
 <div className="cards"><div className="card"><span className="eyebrow">Income</span><strong>{gbp(income)}</strong></div><div className="card"><span className="eyebrow">Expenses</span><strong>{gbp(expenses)}</strong></div><div className="card"><span className="eyebrow">Indicative net</span><strong>{gbp(income-expenses)}</strong></div><div className="card"><span className="eyebrow">Period end</span><strong className="dateValue">{fmtDate(p.periodEnd)}</strong></div></div>
 <section className="panel"><h2>Submission summary</h2><div className="detailGrid"><div><span className="eyebrow">Income source</span><strong>{sourceLabel}</strong></div><div><span className="eyebrow">Business ID</span><strong className="mono">{p.businessId}</strong></div><div><span className="eyebrow">Period</span><strong>{fmtDate(p.periodStart)} to {fmtDate(p.periodEnd)}</strong></div><div><span className="eyebrow">Submission type</span><strong>Cumulative quarterly update</strong></div></div>
 <div className="tableWrap"><table><thead><tr><th>Account</th><th>Amount</th>{!property&&<th>Disallowable</th>}</tr></thead><tbody>{rows.map(([key,label])=><tr key={key}><th>{label}</th><td>{gbp(Number(p[key]||0))}</td>{!property&&<td>{['turnover','otherIncome','taxTakenOff'].includes(key)?'Not applicable':gbp(Number(p[`${key}Disallowable`]||0))}</td>}</tr>)}</tbody></table></div>
 {qs.error&&<div className="status statusError"><strong>Submission needs attention.</strong><div style={{marginTop:5}}>{qs.error}</div>{qs.correlationId&&<div className="muted" style={{marginTop:5}}>HMRC correlation ID: {qs.correlationId}</div>}</div>}
 {hmrcErrors.length>0&&<div className="status statusError"><strong>HMRC rejection details</strong><div style={{marginTop:8}}>{hmrcErrors.map((e:any,i:number)=><div key={`${e.code}-${i}`} style={{marginBottom:12}}><strong>{e.code}</strong>{e.path&&<span className="mono"> · {String(e.path)}</span>}<div>{e.message}</div>{e.guidance&&<div style={{marginTop:5}}><strong>What to do: </strong>{e.guidance}</div>}</div>)}</div><Link className="btn btnSmall" href={editHref}>Correct figures and resubmit</Link></div>}
 {qs.readiness==='blocked'&&<div className="status statusError"><strong>HMRC submission is blocked until all required fraud prevention data can be collected.</strong>{missing.length>0&&<div className="muted" style={{marginTop:6}}>Missing: {missing.join(', ')}</div>}</div>}{qs.submitted&&<div className="status"><strong>HMRC accepted the cumulative quarterly update.</strong>{qs.correlationId&&<div className="muted">Correlation ID: {qs.correlationId}</div>}</div>}
 {!qs.submitted&&<form method="post" action="/api/hmrc/quarterly/submit"><input type="hidden" name="reviewToken" value={token}/><label htmlFor="actingAgentId">Acting as</label><select id="actingAgentId" name="actingAgentId" className="selectField" defaultValue=""><option value="">Taxpayer or direct operator</option>{agents.map((r:any)=><option key={r.agent_id} value={r.agent_id}>{r.mtd_agents?.agent_name||'Authorised agent'}{r.mtd_agents?.organisation_name?` · ${r.mtd_agents.organisation_name}`:''}{r.mtd_agents?.hmrc_arn?` · ARN ${r.mtd_agents.hmrc_arn}`:''}</option>)}</select>{agents.length===0&&<p className="muted">No agent currently has permission to submit quarterly updates for this taxpayer. Manage permissions in Agent Authorisation.</p>}<FraudContextFields/><button className="btn" type="submit">Submit {sourceLabel} update to HMRC sandbox</button></form>}
 <p className="muted">Production submission remains locked. MTD Lab sends only signed review data, complete fraud prevention headers and an audit record.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Link className="btn btnSmall" href={editHref}>Edit figures</Link><Link className="btn btnSmall" href={`/taxpayers/${id}/agents`}>Agent Authorisation</Link><Link className="btn btnSmall" href={`/taxpayers/${id}/quarterly/readiness`}>Check submission readiness</Link><Link className="btn btnSmall" href={`/taxpayers/${id}/quarterly/history`}>View submission history</Link></div></section></main></div>
}
