import Link from 'next/link'
import FraudContextFields from './FraudContextFields'
import { verifyReviewPayload } from '@/lib/review-token'
import TaxpayerSidebar from '@/app/components/TaxpayerSidebar'

function gbp(n:number){return new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(n||0)}
function fmtDate(value?:string){if(!value)return 'Not available';const d=new Date(`${value}T00:00:00`);return Number.isNaN(d.getTime())?value:d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}
function decodeErrors(value?:string){try{return value?JSON.parse(Buffer.from(value,'base64url').toString('utf8')):[]}catch{return []}}

const selfRows=[['turnover','Turnover'],['otherIncome','Other income'],['taxTakenOff','Tax taken off trading income'],['costOfGoods','Cost of goods sold'],['cisPayments','CIS payments to subcontractors'],['staffCosts','Wages and staff costs'],['travelCosts','Car, van and travel expenses'],['premisesCosts','Premises running costs'],['repairsMaintenance','Repairs and maintenance'],['officeCosts','Office costs'],['advertisingCosts','Advertising costs'],['businessEntertainment','Business entertainment'],['interestLoans','Interest on loans'],['financialCharges','Financial charges'],['badDebts','Irrecoverable debts'],['professionalFees','Professional fees'],['depreciation','Depreciation'],['otherExpenses','Other expenses']]
const propertyRows=[['rentalIncome','Rental income'],['leasePremiums','Premiums of lease grant'],['reversePremiums','Reverse premiums'],['otherPropertyIncome','Other property income'],['ukTaxDeducted','UK tax deducted'],['rentARoomReceived','Rent a Room received'],['premisesRunningCosts','Premises running costs'],['repairsMaintenance','Repairs and maintenance'],['financialCosts','Financial costs'],['professionalFees','Professional fees'],['travelCosts','Travel costs'],['costOfServices','Cost of services'],['otherCosts','Other costs'],['rentARoomRelief','Rent a Room relief'],['residentialFinancialCost','Residential financial cost'],['carryForwardResidentialFinanceCost','Residential finance cost carried forward']]

export default async function ReviewPage({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<Record<string,string|undefined>>}){
 const {id}=await params;const qs=await searchParams;const token=String(qs.data||'');const p:any=verifyReviewPayload(token)
 if(!p||p.taxpayerId!==id)return <main className="main"><h1>Quarterly update</h1><p>Review data is missing, invalid or has been altered.</p><Link className="btn" href={`/taxpayers/${id}/submissions`}>Return to Submission Centre</Link></main>
 const property=p.filingType==='property';const rows=property?propertyRows:selfRows
 const incomeKeys=property?['rentalIncome','leasePremiums','reversePremiums','otherPropertyIncome','rentARoomReceived']:['turnover','otherIncome']
 const expenseKeys=property?['premisesRunningCosts','repairsMaintenance','financialCosts','professionalFees','travelCosts','costOfServices','otherCosts','rentARoomRelief','residentialFinancialCost','carryForwardResidentialFinanceCost']:['costOfGoods','cisPayments','staffCosts','travelCosts','premisesCosts','repairsMaintenance','officeCosts','advertisingCosts','businessEntertainment','interestLoans','financialCharges','badDebts','professionalFees','depreciation','otherExpenses']
 const income=incomeKeys.reduce((s,k)=>s+Number(p[k]||0),0);const expenses=expenseKeys.reduce((s,k)=>s+Number(p[k]||0),0);const missing=String(qs.missing||'').split(',').filter(Boolean)
 const hmrcErrors:any[]=decodeErrors(qs.hmrcErrors)
 const editData={...p};delete editData.preparedAt
 const imported=Buffer.from(JSON.stringify(editData),'utf8').toString('base64url')
 const editHref=`/taxpayers/${id}/submissions?type=${property?'property':'self-employment'}&imported=${encodeURIComponent(imported)}&businessId=${encodeURIComponent(p.businessId||'')}&periodStart=${encodeURIComponent(p.periodStart||'')}&periodEnd=${encodeURIComponent(p.periodEnd||'')}`
 return <div className="shell"><TaxpayerSidebar taxpayerId={id} active="submissions"/><main className="main"><div className="top"><div><h1 className="pageTitle">Review {property?'UK property':'self employment'} update</h1><p className="muted">Check these cumulative figures before HMRC submission.</p></div><span className="badge">{qs.submitted?'Submitted':'Not submitted'}</span></div>
 <div className="cards"><div className="card"><span className="eyebrow">Income</span><strong>{gbp(income)}</strong></div><div className="card"><span className="eyebrow">Expenses and reliefs</span><strong>{gbp(expenses)}</strong></div><div className="card"><span className="eyebrow">Indicative net</span><strong>{gbp(income-expenses)}</strong></div><div className="card"><span className="eyebrow">Period end</span><strong className="dateValue">{fmtDate(p.periodEnd)}</strong></div></div>
 <section className="panel"><h2>Submission summary</h2><div className="detailGrid"><div><span className="eyebrow">Income source</span><strong>{property?'UK Property':'Self Employment'}</strong></div><div><span className="eyebrow">Business ID</span><strong className="mono">{p.businessId}</strong></div><div><span className="eyebrow">Period</span><strong>{fmtDate(p.periodStart)} to {fmtDate(p.periodEnd)}</strong></div><div><span className="eyebrow">Submission type</span><strong>Cumulative quarterly update</strong></div></div>
 <div className="tableWrap"><table><thead><tr><th>Account</th><th>Amount</th>{!property&&<th>Disallowable</th>}</tr></thead><tbody>{rows.map(([key,label])=><tr key={key}><th>{label}</th><td>{gbp(Number(p[key]||0))}</td>{!property&&<td>{['turnover','otherIncome','taxTakenOff'].includes(key)?'Not applicable':gbp(Number(p[`${key}Disallowable`]||0))}</td>}</tr>)}</tbody></table></div>
 {qs.error&&<div className="status statusError"><strong>Submission needs attention.</strong><div style={{marginTop:5}}>{qs.error}</div>{qs.correlationId&&<div className="muted" style={{marginTop:5}}>HMRC correlation ID: {qs.correlationId}</div>}</div>}
 {hmrcErrors.length>0&&<div className="status statusError"><strong>HMRC rejection details</strong><div style={{marginTop:8}}>{hmrcErrors.map((e:any,i:number)=><div key={`${e.code}-${i}`} style={{marginBottom:8}}><strong>{e.code}</strong>{e.path&&<span className="mono"> · {Array.isArray(e.path)?e.path.join(', '):String(e.path)}</span>}<div>{e.message}</div></div>)}</div><Link className="btn btnSmall" href={editHref}>Correct figures and resubmit</Link></div>}
 {qs.readiness==='blocked'&&<div className="status statusError"><strong>HMRC submission is blocked until all required fraud prevention data can be collected.</strong>{missing.length>0&&<div className="muted" style={{marginTop:6}}>Missing: {missing.join(', ')}</div>}</div>}{qs.submitted&&<div className="status"><strong>HMRC accepted the cumulative quarterly update.</strong>{qs.correlationId&&<div className="muted">Correlation ID: {qs.correlationId}</div>}</div>}
 {!qs.submitted&&<form method="post" action="/api/hmrc/quarterly/submit"><input type="hidden" name="reviewToken" value={token}/><FraudContextFields/><button className="btn" type="submit">Submit {property?'UK property':'self employment'} update to HMRC sandbox</button></form>}
 <p className="muted">Production submission remains locked. MTD Lab sends only signed review data, complete fraud prevention headers and an audit record.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Link className="btn btnSmall" href={editHref}>Edit figures</Link><Link className="btn btnSmall" href={`/taxpayers/${id}/quarterly/readiness`}>Check submission readiness</Link><Link className="btn btnSmall" href={`/taxpayers/${id}/quarterly/history`}>View submission history</Link></div></section></main></div>
}
