import Link from 'next/link'
import TaxpayerSidebar from '@/app/components/TaxpayerSidebar'
import FraudContextFields from '@/app/components/FraudContextFields'
import { supabaseAdmin } from '@/lib/supabase-admin'
import { latestHmrcResponse } from '@/lib/hmrc-response-audit'

export const dynamic='force-dynamic'
const labels:Record<string,string>={investment:'Investment Reliefs',other:'Other Reliefs',foreign:'Foreign Reliefs',pensions:'Pension Reliefs',charitable:'Charitable Giving'}
const money=(name:string,label:string)=><label>{label}<input className="inputField" name={name} type="number" min="0" step="0.01"/></label>

export default async function ReliefsPage({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<Record<string,string|undefined>>}){
 const {id}=await params;const qs=await searchParams;const db=supabaseAdmin();const {data:obligations}=await db.from('hmrc_obligations').select('period_start').eq('taxpayer_id',id).gte('period_start','2025-04-06')
 const years=Array.from(new Set((obligations||[]).map((o:any)=>{const d=String(o.period_start);const y=Number(d.slice(0,4));return `${y}-${String(y+1).slice(-2)}`}))).sort().reverse();const selected=qs.taxYear&&years.includes(qs.taxYear)?qs.taxYear:(years[0]||'2026-27');const type=labels[qs.type||'other']?String(qs.type):'other';const stored=await latestHmrcResponse(db,{taxpayerId:id,taxYear:selected,eventType:'reliefs_retrieval',requestKey:'type',requestValue:type});const result=stored?.response_summary||stored?.response_payload||null
 return <div className="shell"><TaxpayerSidebar taxpayerId={id} active="reliefs"/><main className="main">
  <div className="top"><div><h1 className="pageTitle">Reliefs and Deductions</h1><p className="muted">Review, create and amend relief information before the end of year calculation and Final Declaration.</p></div><span className="badge">{selected}</span></div>
  {qs.error&&<div className="status statusError"><strong>HMRC needs attention.</strong><div>{qs.error}</div>{qs.correlationId&&<div className="muted">Correlation ID: {qs.correlationId}</div>}</div>}
  {(qs.saved||qs.savedPensions||qs.savedForeign||qs.savedInvestment||qs.savedOther)&&<div className="status"><strong>Relief information saved to HMRC.</strong>{qs.correlationId&&<div className="muted">Correlation ID: {qs.correlationId}</div>}</div>}
  <section className="panel"><div className="sectionHead"><div><h2>HMRC relief schedules</h2><p className="muted">Retrieve each relief category that applies. Successful retrievals and successful amendments mark the Reliefs schedule as reviewed in End of Year.</p></div><form method="get"><select className="selectField" name="taxYear" defaultValue={selected}>{years.length?years.map(y=><option key={y} value={y}>{y}</option>):<option value={selected}>{selected}</option>}</select><button className="btn btnSmall" type="submit">Change year</button></form></div><div className="cards">{Object.entries(labels).map(([key,label])=><div className="card" key={key}><span className="eyebrow">{label}</span><p className="muted">Retrieve the current HMRC record for {selected}.</p><Link className="btn btnSmall" href={`/api/hmrc/reliefs/retrieve?taxpayerId=${encodeURIComponent(id)}&taxYear=${encodeURIComponent(selected)}&type=${encodeURIComponent(key)}`}>Retrieve from HMRC</Link></div>)}</div></section>
  {qs.retrieved&&result&&<section className="panel" style={{marginTop:16}}><div className="sectionHead"><div><h2>{labels[type]}</h2><p className="muted">Retrieved directly from HMRC.</p></div>{qs.correlationId&&<span className="badge">Correlation {qs.correlationId}</span>}</div><details open><summary>HMRC response</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(result,null,2)}</pre></details></section>}

  <section className="panel" style={{marginTop:16}}><h2>Charitable Giving</h2><form method="post" action="/api/hmrc/reliefs/charitable/amend"><input type="hidden" name="taxpayerId" value={id}/><input type="hidden" name="taxYear" value={selected}/><FraudContextFields/><div className="cards"><div className="card"><span className="eyebrow">Gift Aid</span>{money('totalAmount','Total amount')}{money('oneOffAmount','One off amount')}{money('amountTreatedAsPreviousTaxYear','Treated as previous tax year')}{money('amountTreatedAsSpecifiedTaxYear','Treated as specified tax year')}</div><div className="card"><span className="eyebrow">Qualifying gifts</span>{money('landAndBuildings','Land and buildings')}{money('sharesOrSecurities','Shares or securities')}</div></div><button className="btn" type="submit" style={{marginTop:12}}>Save Charitable Giving to HMRC</button></form></section>

  <section className="panel" style={{marginTop:16}}><h2>Pension Reliefs</h2><form method="post" action="/api/hmrc/reliefs/pensions/amend"><input type="hidden" name="taxpayerId" value={id}/><input type="hidden" name="taxYear" value={selected}/><FraudContextFields/><div className="cards"><div className="card"><span className="eyebrow">Pension contributions</span>{money('regularPensionContributions','Regular pension contributions')}{money('oneOffPensionContributionsPaid','One off pension contributions paid')}{money('retirementAnnuityPayments','Retirement annuity payments')}</div><div className="card"><span className="eyebrow">Other pension relief</span>{money('paymentToEmployersSchemeNoTaxRelief','Employer scheme payment with no tax relief')}{money('overseasPensionSchemeContributions','Overseas pension scheme contributions')}</div></div><button className="btn" type="submit" style={{marginTop:12}}>Save Pension Reliefs to HMRC</button></form></section>

  <section className="panel" style={{marginTop:16}}><h2>Foreign Reliefs</h2><p className="muted">Create or amend Foreign Tax Credit Relief and country specific foreign income tax credit relief.</p><form method="post" action="/api/hmrc/reliefs/foreign/amend"><input type="hidden" name="taxpayerId" value={id}/><input type="hidden" name="taxYear" value={selected}/><FraudContextFields/><div className="cards"><div className="card"><span className="eyebrow">Foreign Tax Credit Relief</span>{money('foreignTaxCreditReliefAmount','Relief amount')}{money('foreignTaxForFtcrNotClaimedAmount','Foreign tax where FTCR not claimed')}</div><div className="card"><span className="eyebrow">Country specific claim</span><label>Country code<input className="inputField" name="countryCode" placeholder="FRA" maxLength={3}/></label>{money('taxableAmount','Taxable amount')}{money('foreignTaxPaid','Foreign tax paid')}<label>Employment lump sum<select className="selectField" name="employmentLumpSum" defaultValue="false"><option value="false">No</option><option value="true">Yes</option></select></label></div></div><button className="btn" type="submit" style={{marginTop:12}}>Save Foreign Reliefs to HMRC</button></form></section>

  <section className="panel" style={{marginTop:16}}><h2>Investment Reliefs</h2><p className="muted">Enter one claim in any applicable investment category. Each complete category is sent as its own HMRC subscription item.</p><form method="post" action="/api/hmrc/reliefs/investment/amend"><input type="hidden" name="taxpayerId" value={id}/><input type="hidden" name="taxYear" value={selected}/><FraudContextFields/><div className="cards">
   {([['vct','Venture Capital Trust'],['eis','Enterprise Investment Scheme'],['community','Community Investment']] as string[][]).map(([p,title])=><div className="card" key={p}><span className="eyebrow">{title}</span><label>Investment reference<input className="inputField" name={`${p}Ref`}/></label><label>Name<input className="inputField" name={`${p}Name`}/></label><label>Date of investment<input className="inputField" name={`${p}Date`} type="date"/></label>{money(`${p}Amount`,'Amount invested')}{money(`${p}Relief`,'Relief claimed')}{p==='eis'&&<label>Knowledge intensive<select className="selectField" name="eisKnowledgeIntensive" defaultValue="false"><option value="false">No</option><option value="true">Yes</option></select></label>}</div>)}
   <div className="card"><span className="eyebrow">Seed Enterprise Investment Scheme</span><label>Investment reference<input className="inputField" name="seedRef"/></label><label>Company name<input className="inputField" name="seedCompanyName"/></label><label>Date of investment<input className="inputField" name="seedDate" type="date"/></label>{money('seedAmount','Amount invested')}{money('seedRelief','Relief claimed')}</div>
  </div><button className="btn" type="submit" style={{marginTop:12}}>Save Investment Reliefs to HMRC</button></form></section>

  <section className="panel" style={{marginTop:16}}><h2>Other Reliefs</h2><p className="muted">Use only the categories that apply to the taxpayer. Each partially completed category is rejected before HMRC submission.</p><form method="post" action="/api/hmrc/reliefs/other/amend"><input type="hidden" name="taxpayerId" value={id}/><input type="hidden" name="taxYear" value={selected}/><FraudContextFields/><div className="cards">
   {([['nonDeductible','Non deductible loan interest'],['payrollGiving','Payroll giving'],['qualifyingDistribution','Qualifying distribution or redemption'],['annualPayments','Annual payments made']] as string[][]).map(([p,title])=><div className="card" key={p}><span className="eyebrow">{title}</span><label>Customer reference<input className="inputField" name={`${p}Ref`}/></label>{money(`${p}Amount`,p==='qualifyingDistribution'?'Amount':'Relief claimed')}</div>)}
   <div className="card"><span className="eyebrow">Maintenance payments</span><label>Customer reference<input className="inputField" name="maintenanceRef"/></label><label>Ex spouse name<input className="inputField" name="maintenanceName"/></label><label>Ex spouse date of birth<input className="inputField" name="maintenanceDob" type="date"/></label>{money('maintenanceAmount','Amount')}</div>
   <div className="card"><span className="eyebrow">Post cessation trade relief and other losses</span><label>Customer reference<input className="inputField" name="postCessationRef"/></label><label>Business name<input className="inputField" name="postCessationBusinessName"/></label><label>Date business ceased<input className="inputField" name="postCessationDate" type="date"/></label><label>Nature of trade<input className="inputField" name="postCessationTrade"/></label><label>Income source<input className="inputField" name="postCessationIncomeSource"/></label>{money('postCessationAmount','Amount')}</div>
   <div className="card"><span className="eyebrow">Qualifying loan interest</span><label>Customer reference<input className="inputField" name="qualifyingLoanRef"/></label><label>Lender name<input className="inputField" name="qualifyingLoanLender"/></label>{money('qualifyingLoanAmount','Relief claimed')}</div>
  </div><button className="btn" type="submit" style={{marginTop:12}}>Save Other Reliefs to HMRC</button></form></section>

  <section className="panel" style={{marginTop:16}}><h2>Year end control</h2><p className="muted">All five HMRC relief schedules now support retrieval, and the main writable categories are available as separate validated forms. Successful activity automatically updates the End of Year review state.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Link className="btn btnSmall" href={`/taxpayers/${id}/end-of-year?taxYear=${encodeURIComponent(selected)}`}>Back to End of Year</Link><Link className="btn btnSmall" href={`/taxpayers/${id}/calculations?taxYear=${encodeURIComponent(selected)}`}>HMRC Tax Calculation</Link></div></section>
 </main></div>
}
