import Link from 'next/link'
import TaxpayerSidebar from '@/app/components/TaxpayerSidebar'
import FraudContextFields from '@/app/components/FraudContextFields'
import { supabaseAdmin } from '@/lib/supabase-admin'
import { latestHmrcResponse } from '@/lib/hmrc-response-audit'

export const dynamic='force-dynamic'
function isProperty(b:any){const t=String(b.business_type||'').toLowerCase();const r=JSON.stringify(b.raw||{}).toLowerCase();return t.includes('property')||r.includes('uk-property')||r.includes('property')}
function gbp(v:any){return new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(Number(v||0))}
const money=(name:string,label:string)=><label>{label}<input className="inputField" name={name} inputMode="decimal" placeholder="0.00"/></label>
const detailed=[['costOfGoods','Cost of goods'],['paymentsToSubcontractors','Payments to subcontractors'],['wagesAndStaffCosts','Wages and staff costs'],['carVanTravelExpenses','Car, van and travel'],['premisesRunningCosts','Premises running costs'],['maintenanceCosts','Repairs and maintenance'],['adminCosts','Admin and office costs'],['interestOnBankOtherLoans','Interest on bank and other loans'],['financeCharges','Finance charges'],['irrecoverableDebts','Irrecoverable debts'],['professionalFees','Professional fees'],['depreciation','Depreciation'],['otherExpenses','Other expenses'],['advertisingCosts','Advertising costs'],['businessEntertainmentCosts','Business entertainment']]

export default async function AdjustmentsPage({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<Record<string,string|undefined>>}){
 const {id}=await params;const qs=await searchParams;const db=supabaseAdmin();const [{data:taxpayer},{data:businesses},{data:obligations}]=await Promise.all([db.from('taxpayers').select('display_name,nino').eq('id',id).maybeSingle(),db.from('hmrc_businesses').select('*').eq('taxpayer_id',id).order('created_at'),db.from('hmrc_obligations').select('period_start').eq('taxpayer_id',id).gte('period_start','2025-04-06')])
 const years=Array.from(new Set((obligations||[]).map((o:any)=>{const d=String(o.period_start);const y=Number(d.slice(0,4));return `${y}-${String(y+1).slice(-2)}`}))).sort().reverse();const selected=qs.taxYear&&years.includes(qs.taxYear)?qs.taxYear:(years[0]||'2026-27');const storedLoss=qs.lossBusinessId?await latestHmrcResponse(db,{taxpayerId:id,taxYear:selected,eventType:'losses_retrieval',requestKey:'businessId',requestValue:qs.lossBusinessId}):null;const lossResult:any=storedLoss?.response_summary||storedLoss?.response_payload||null;const bsasType=qs.businessType||'self-employment'
 return <div className="shell"><TaxpayerSidebar taxpayerId={id} active="adjustments"/><main className="main">
  <div className="top"><div><h1 className="pageTitle">Annual Adjustments and Losses</h1><p className="muted">Prepare year end business adjustments and review or amend HMRC losses before intent to finalise.</p></div><span className="badge">{selected}</span></div>
  {qs.error&&<div className="status statusError"><strong>HMRC needs attention.</strong><div>{qs.error}</div>{qs.correlationId&&<div className="muted">Correlation ID: {qs.correlationId}</div>}</div>}
  {qs.bsasTriggered&&<div className="status"><strong>HMRC generated a Business Source Adjustable Summary.</strong>{qs.calculationId&&<div>BSAS calculation ID: <span className="mono">{qs.calculationId}</span></div>}<div className="muted">Use the form below to submit accounting adjustments against this BSAS.</div></div>}
  {qs.adjustmentSubmitted&&<div className="status"><strong>Accounting adjustments accepted by HMRC.</strong>{qs.correlationId&&<div className="muted">Correlation ID: {qs.correlationId}</div>}</div>}
  {qs.lossSaved&&<div className="status"><strong>Losses and claims saved with HMRC.</strong>{qs.correlationId&&<div className="muted">Correlation ID: {qs.correlationId}</div>}</div>}
  <section className="panel"><div className="sectionHead"><div><h2>Business Source Adjustable Summary</h2><p className="muted">Generate one summary for each business that needs year end accounting adjustments.</p></div><form method="get"><select className="selectField" name="taxYear" defaultValue={selected}>{years.map(y=><option key={y} value={y}>{y}</option>)}</select><button className="btn btnSmall" type="submit">Change year</button></form></div><div className="tableWrap"><table><thead><tr><th>Income source</th><th>Business</th><th>Business ID</th><th>Year end adjustment</th></tr></thead><tbody>{(businesses||[]).length?(businesses||[]).map((b:any)=>{const property=isProperty(b);return <tr key={b.id}><td>{property?'UK Property':'Self Employment'}</td><td>{b.business_name||'HMRC business'}</td><td className="mono">{b.business_id}</td><td><form method="post" action="/api/hmrc/bsas/trigger"><input type="hidden" name="taxpayerId" value={id}/><input type="hidden" name="taxYear" value={selected}/><input type="hidden" name="businessId" value={b.business_id}/><input type="hidden" name="typeOfBusiness" value={property?'uk-property':'self-employment'}/><FraudContextFields/><button className="btn btnSmall" type="submit">Generate adjustable summary</button></form></td></tr>}):<tr><td colSpan={4} className="empty">No HMRC businesses are available.</td></tr>}</tbody></table></div></section>
  {qs.calculationId&&<section className="panel" style={{marginTop:16}}><h2>Enter accounting adjustments</h2><p className="muted">Enter adjustment amounts only. HMRC applies these against the generated BSAS. Review carefully because a BSAS can only be adjusted once.</p><form method="post" action="/api/hmrc/bsas/adjust"><input type="hidden" name="taxpayerId" value={id}/><input type="hidden" name="taxYear" value={selected}/><input type="hidden" name="calculationId" value={qs.calculationId}/><input type="hidden" name="typeOfBusiness" value={bsasType}/>
   {bsasType==='uk-property'?<><h3>UK Property income adjustments</h3><div className="formGrid">{money('totalRentsReceived','Total rents received')}{money('premiumsOfLeaseGrant','Premiums of lease grant')}{money('reversePremiums','Reverse premiums')}{money('otherPropertyIncome','Other property income')}</div><h3>UK Property expense adjustments</h3><div className="formGrid">{money('premisesRunningCosts','Premises running costs')}{money('repairsAndMaintenance','Repairs and maintenance')}{money('financialCosts','Financial costs')}{money('professionalFees','Professional fees')}{money('costOfServices','Cost of services')}{money('residentialFinancialCost','Residential financial cost')}{money('travelCosts','Travel costs')}{money('otherPropertyExpenses','Other expenses')}</div></>:<><h3>Self Employment adjustments</h3><div className="formGrid">{money('turnover','Turnover adjustment')}{money('otherIncome','Other income adjustment')}</div><label>Expense adjustment method</label><select className="selectField" name="expenseMode" defaultValue="detailed"><option value="detailed">Detailed expenses</option><option value="consolidated">Consolidated expenses</option></select><div className="formGrid">{money('consolidatedExpenses','Consolidated expenses adjustment')}</div><h3>Detailed expense adjustments</h3><div className="formGrid">{detailed.map(([n,l])=><div key={n}>{money(n,l)}</div>)}</div><h3>Disallowable additions</h3><div className="formGrid">{detailed.map(([n,l])=><div key={n+'Disallowable'}>{money(n+'Disallowable',l+' disallowable')}</div>)}</div><p className="muted">Choose one expense method only. MTD Lab sends either consolidated expenses or detailed expense categories to HMRC, never both.</p></>}
   <FraudContextFields/><button className="btn" type="submit">Submit accounting adjustments to HMRC</button></form></section>}
  <section className="panel" style={{marginTop:16}}><h2>Losses and claims</h2><p className="muted">Retrieve existing HMRC losses, or create and amend loss information for a business. HMRC normally permits writes only after the tax year has ended.</p><div className="tableWrap"><table><thead><tr><th>Business</th><th>Income source</th><th>Action</th></tr></thead><tbody>{(businesses||[]).map((b:any)=><tr key={b.id}><td>{b.business_name||b.business_id}</td><td>{isProperty(b)?'UK Property':'Self Employment'}</td><td><form method="post" action="/api/hmrc/losses/retrieve"><input type="hidden" name="taxpayerId" value={id}/><input type="hidden" name="taxYear" value={selected}/><input type="hidden" name="businessId" value={b.business_id}/><FraudContextFields/><button className="btn btnSmall" type="submit">Retrieve losses and claims</button></form></td></tr>)}</tbody></table></div>
   {qs.lossesRetrieved&&lossResult&&<div style={{marginTop:18}}><h3>HMRC losses and claims</h3><div className="cards"><div className="card"><span className="eyebrow">Brought forward losses</span><strong>{gbp(lossResult?.losses?.broughtForwardLosses)}</strong></div><div className="card"><span className="eyebrow">Current year loss carried forward</span><strong>{gbp(lossResult?.claims?.carryForward?.currentYearLosses)}</strong></div><div className="card"><span className="eyebrow">Previous years losses carried forward</span><strong>{gbp(lossResult?.claims?.carryForward?.previousYearsLosses)}</strong></div><div className="card"><span className="eyebrow">Current year general income claim</span><strong>{gbp(lossResult?.claims?.carrySideways?.currentYearGeneralIncome)}</strong></div></div><details style={{marginTop:12}}><summary>View full HMRC loss response</summary><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(lossResult,null,2)}</pre></details></div>}
   <h3 style={{marginTop:22}}>Create or amend losses and claims</h3><div className="cards">{(businesses||[]).map((b:any)=>{const property=isProperty(b);return <div className="card" key={'loss-'+b.id}><strong>{b.business_name||b.business_id}</strong><p className="muted">{property?'UK Property':'Self Employment'}</p><form method="post" action="/api/hmrc/losses/create-amend"><input type="hidden" name="taxpayerId" value={id}/><input type="hidden" name="taxYear" value={selected}/><input type="hidden" name="businessId" value={b.business_id}/><input type="hidden" name="businessType" value={property?'uk-property':'self-employment'}/><div className="formGrid">{money('broughtForwardLosses','Brought forward losses')}{money('carryForwardCurrentYearLosses','Current year losses to carry forward')}{money('carryForwardPreviousYearsLosses','Previous years losses to carry forward')}{money('carrySidewaysCurrentYearGeneralIncome','Claim against current year general income')}{!property&&money('carryBackPreviousYearGeneralIncome','Carry back to previous year general income')}{!property&&money('carryBackEarlyYearLosses','Early year losses carry back')}</div>{!property&&<><label>Preference order</label><select className="selectField" name="preferenceOrder" defaultValue=""><option value="">Select only when required</option><option value="carry-sideways">Carry sideways first</option><option value="carry-back">Carry back first</option></select></>}<FraudContextFields/><button className="btn btnSmall" type="submit">Save losses and claims with HMRC</button></form></div>})}</div>
  </section>
  <div style={{marginTop:16,display:'flex',gap:8,flexWrap:'wrap'}}><Link className="btn btnSmall" href={`/taxpayers/${id}/end-of-year?taxYear=${encodeURIComponent(selected)}`}>Back to End of Year</Link><Link className="btn btnSmall" href={`/taxpayers/${id}/calculations?taxYear=${encodeURIComponent(selected)}`}>HMRC Tax Calculation</Link></div>
 </main></div>
}
