import Link from 'next/link'
import TaxpayerSidebar from '@/app/components/TaxpayerSidebar'
import { supabaseAdmin } from '@/lib/supabase-admin'
import { latestHmrcResponse } from '@/lib/hmrc-response-audit'

export const dynamic='force-dynamic'

export default async function EmploymentPage({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<Record<string,string|undefined>>}){
 const {id}=await params;const qs=await searchParams;const db=supabaseAdmin();const {data:obligations}=await db.from('hmrc_obligations').select('period_start').eq('taxpayer_id',id).gte('period_start','2025-04-06')
 const years=Array.from(new Set((obligations||[]).map((o:any)=>{const d=String(o.period_start);const y=Number(d.slice(0,4));return `${y}-${String(y+1).slice(-2)}`}))).sort().reverse();const selected=qs.taxYear&&years.includes(qs.taxYear)?qs.taxYear:(years[0]||'2026-27');const employmentList=await latestHmrcResponse(db,{taxpayerId:id,taxYear:selected,eventType:'employment_list_retrieval'});const financialRow=qs.employmentId?await latestHmrcResponse(db,{taxpayerId:id,taxYear:selected,eventType:'employment_financial_retrieval',requestKey:'employmentId',requestValue:qs.employmentId}):null;const result:any=employmentList?.response_summary||employmentList?.response_payload||null;const financial:any=financialRow?.response_summary||financialRow?.response_payload||null;const employments=Array.isArray(result?.employments)?result.employments:[]
 return <div className="shell"><TaxpayerSidebar taxpayerId={id} active="employment"/><main className="main">
  <div className="top"><div><h1 className="pageTitle">Employment Income</h1><p className="muted">Review HMRC employment and occupational pension sources before the end of year calculation.</p></div><span className="badge">{selected}</span></div>
  {qs.error&&<div className="status statusError"><strong>HMRC needs attention.</strong><div>{qs.error}</div>{qs.correlationId&&<div className="muted">Correlation ID: {qs.correlationId}</div>}</div>}
  <section className="panel"><div className="sectionHead"><div><h2>HMRC employments</h2><p className="muted">List PAYE and custom employment records for the selected tax year.</p></div><form method="get"><select className="selectField" name="taxYear" defaultValue={selected}>{years.length?years.map(y=><option key={y} value={y}>{y}</option>):<option value={selected}>{selected}</option>}</select><button className="btn btnSmall" type="submit">Change year</button></form></div><Link className="btn" href={`/api/hmrc/employments/list?taxpayerId=${encodeURIComponent(id)}&taxYear=${encodeURIComponent(selected)}`}>Retrieve employments from HMRC</Link></section>
  {qs.retrieved&&result&&<section className="panel" style={{marginTop:16}}><div className="sectionHead"><div><h2>Employment sources</h2><p className="muted">Retrieved directly from HMRC.</p></div>{qs.correlationId&&<span className="badge">Correlation {qs.correlationId}</span>}</div>{employments.length?<div className="tableWrap"><table><thead><tr><th>Employer</th><th>Employment ID</th><th>Payroll ID</th><th>Occupational pension</th><th>Financial details</th></tr></thead><tbody>{employments.map((e:any,i:number)=><tr key={e.employmentId||i}><td>{e.employerName||e.employerRef||'Employment'}</td><td className="mono">{e.employmentId||'Not supplied'}</td><td>{e.payrollId||'Not supplied'}</td><td>{e.occupationalPension?'Yes':'No'}</td><td>{e.employmentId?<Link className="btn btnSmall" href={`/api/hmrc/employments/financial-details?taxpayerId=${encodeURIComponent(id)}&taxYear=${encodeURIComponent(selected)}&employmentId=${encodeURIComponent(e.employmentId)}`}>Retrieve details</Link>:<span className="muted">Unavailable</span>}</td></tr>)}</tbody></table></div>:<div className="status">HMRC returned an employment response. Expand the full response below to review its structure.</div>}<details style={{marginTop:12}}><summary>View full HMRC response</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(result,null,2)}</pre></details></section>}
  {qs.financial&&financial&&<section className="panel" style={{marginTop:16}}><div className="sectionHead"><div><h2>Employment financial details</h2><p className="muted">Employment ID: <span className="mono">{qs.employmentId}</span></p></div>{qs.correlationId&&<span className="badge">Correlation {qs.correlationId}</span>}</div><div className="cards"><div className="card"><span className="eyebrow">Taxable pay</span><strong>{financial?.pay?.taxablePayToDate??financial?.employment?.pay?.taxablePayToDate??'See HMRC response'}</strong></div><div className="card"><span className="eyebrow">Total tax</span><strong>{financial?.pay?.totalTaxToDate??financial?.employment?.pay?.totalTaxToDate??'See HMRC response'}</strong></div><div className="card"><span className="eyebrow">Benefits and expenses</span><strong>{financial?.benefitsInKind?'HMRC data found':'Review response'}</strong></div></div><details style={{marginTop:12}} open><summary>View HMRC financial details</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(financial,null,2)}</pre></details></section>}
  <section className="panel" style={{marginTop:16}}><h2>Year end control</h2><p className="muted">Employment sources and their financial details can now be reviewed directly. The next stage will add controlled write forms for custom employment adjustments, Non PAYE employment income and other employment income where applicable.</p><Link className="btn btnSmall" href={`/taxpayers/${id}/end-of-year?taxYear=${encodeURIComponent(selected)}`}>Back to End of Year</Link></section>
 </main></div>
}
