import Link from 'next/link'
import { supabaseAdmin } from '@/lib/supabase-admin'
import TaxpayerSidebar from '@/app/components/TaxpayerSidebar'

export const dynamic='force-dynamic'

function fmtDate(value?:string|null){if(!value)return 'Not available';const d=new Date(`${value}T00:00:00`);return Number.isNaN(d.getTime())?value:d.toLocaleDateString('en-GB',{day:'2-digit',month:'2-digit',year:'numeric'})}
function fmtDateTime(value?:string|null){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString('en-GB')}
function taxYearFor(value?:string|null){if(!value)return '';const [y,m,d]=value.split('-').map(Number);const start=m>4||(m===4&&d>=6)?y:y-1;return `${start}/${String(start+1).slice(-2)}`}
function visualStatus(o:any){const hmrc=String(o.status||'').toLowerCase();if(hmrc==='fulfilled')return {label:'Fulfilled',cls:'statusDone'};const due=o.due_date?new Date(`${o.due_date}T23:59:59Z`):null;const now=new Date();if(due&&due<now)return {label:'Overdue',cls:'statusError'};if(due&&due.getTime()-now.getTime()<1000*60*60*24*30)return {label:'Due soon',cls:'statusOpen'};return {label:'Not due yet',cls:'statusOpen'}}

export default async function QuarterlyPage({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<Record<string,string|undefined>>}){
 const {id}=await params;const qs=await searchParams;const db=supabaseAdmin()
 const [{data:taxpayer},{data:businesses},{data:obligations},{data:submissions}]=await Promise.all([
  db.from('taxpayers').select('*').eq('id',id).maybeSingle(),
  db.from('hmrc_businesses').select('*').eq('taxpayer_id',id).order('created_at'),
  db.from('hmrc_obligations').select('*').eq('taxpayer_id',id).gte('period_start','2025-04-06').order('period_end'),
  db.from('hmrc_quarterly_submissions').select('*').eq('taxpayer_id',id).order('created_at',{ascending:false})
 ])
 const selectedBusiness=qs.businessId||businesses?.[0]?.business_id||''
 const rows=(obligations||[]).filter((o:any)=>!selectedBusiness||!o.business_id||o.business_id===selectedBusiness)
 const selectedPeriodEnd=qs.periodEnd||''
 const selectedObligation=rows.find((o:any)=>o.period_end===selectedPeriodEnd&&String(o.status).toLowerCase()==='open')
 const latestSubmission=(periodEnd:string)=>(submissions||[]).find((s:any)=>s.business_id===selectedBusiness&&s.period_end===periodEnd&&s.status==='submitted')
 const quarterRows=rows.map((o:any,index:number)=>({o,quarter:index+1,submission:latestSubmission(o.period_end)}))
 return <div className="shell"><TaxpayerSidebar taxpayerId={id} active="quarterly"/><main className="main"><div className="top"><div><h1 className="pageTitle">Quarterly Obligations</h1><p className="muted">Retrieve, review and submit cumulative MTD Income Tax updates.</p></div><span className="badge">Sandbox</span></div>
 <section className="panel" style={{marginTop:20,marginBottom:16}}><div className="sectionHead"><div><h2>{taxpayer?.display_name||'Taxpayer'}</h2><p className="muted">Select an HMRC income source to view its quarterly obligations.</p></div><div style={{display:'flex',gap:8,alignItems:'end',flexWrap:'wrap'}}><form method="get" className="filterForm" style={{minWidth:360}}><label htmlFor="businessId">Business</label><select id="businessId" name="businessId" className="selectField" defaultValue={selectedBusiness}>{(businesses||[]).map((b:any)=><option key={b.id} value={b.business_id}>{b.business_name||b.business_id}</option>)}</select><button className="btn btnSmall" type="submit">Select</button></form><form method="post" action="/api/hmrc/sync"><input type="hidden" name="taxpayerId" value={id}/><input type="hidden" name="nino" value={taxpayer?.nino||''}/><input type="hidden" name="mtditid" value={taxpayer?.mtditid||''}/><button className="btn btnSmall" type="submit">↻ Retrieve Obligations</button></form></div></div></section>
 <section className="panel"><div className="tableWrap"><table><thead><tr><th>Period</th><th>Period Dates</th><th>Due Date</th><th>Submission Date & Time</th><th>Status</th><th>Action</th></tr></thead><tbody>{quarterRows.length?quarterRows.map(({o,quarter,submission}:any)=>{const st=visualStatus(o);const fulfilled=String(o.status).toLowerCase()==='fulfilled';return <tr key={o.id}><td><strong>Quarter {quarter}</strong></td><td>{fmtDate(o.period_start)} to {fmtDate(o.period_end)}</td><td>{fmtDate(o.due_date)}</td><td>{fmtDateTime(submission?.submitted_at)}</td><td><span className={`statusPill ${st.cls}`}>{st.label}</span></td><td>{fulfilled?<Link className="btn btnSmall" href={`/taxpayers/${id}/quarterly/history`}>View</Link>:<Link className="btn btnSmall" href={`/taxpayers/${id}/quarterly?businessId=${encodeURIComponent(selectedBusiness)}&periodEnd=${encodeURIComponent(o.period_end)}`}>Submit</Link>}</td></tr>}):<tr><td colSpan={6} className="empty">No eligible quarterly obligations are available for this business.</td></tr>}</tbody></table></div></section>
 {selectedObligation&&<section className="panel" style={{marginTop:16}}><div className="sectionHead"><div><h2>Prepare Quarter {Math.max(1,quarterRows.find((x:any)=>x.o.id===selectedObligation.id)?.quarter||1)} cumulative update</h2><p className="muted">Enter cumulative totals from 6 April {taxYearFor(selectedObligation.period_start).split('/')[0]} to {fmtDate(selectedObligation.period_end)}.</p></div><Link className="btn btnSmall" href={`/taxpayers/${id}/quarterly?businessId=${encodeURIComponent(selectedBusiness)}`}>Close</Link></div><form method="post" action="/api/hmrc/quarterly/prepare"><input type="hidden" name="taxpayerId" value={id}/><input type="hidden" name="businessId" value={selectedBusiness}/><input type="hidden" name="periodStart" value={selectedObligation.period_start}/><input type="hidden" name="periodEnd" value={selectedObligation.period_end}/><div className="two"><div><label>Turnover / income (£)</label><input className="field" name="turnover" type="number" min="0" step="0.01" required/></div><div><label>Other business income (£)</label><input className="field" name="otherIncome" type="number" min="0" step="0.01" defaultValue="0"/></div></div><h3>Allowable expenses</h3><div className="two"><div><label>Cost of goods (£)</label><input className="field" name="costOfGoods" type="number" min="0" step="0.01" defaultValue="0"/><label>Staff costs (£)</label><input className="field" name="staffCosts" type="number" min="0" step="0.01" defaultValue="0"/><label>Travel costs (£)</label><input className="field" name="travelCosts" type="number" min="0" step="0.01" defaultValue="0"/></div><div><label>Premises costs (£)</label><input className="field" name="premisesCosts" type="number" min="0" step="0.01" defaultValue="0"/><label>Professional fees (£)</label><input className="field" name="professionalFees" type="number" min="0" step="0.01" defaultValue="0"/><label>Other expenses (£)</label><input className="field" name="otherExpenses" type="number" min="0" step="0.01" defaultValue="0"/></div></div><button className="btn" type="submit">Review quarterly update</button></form></section>}
 </main></div>
}
