import { NextResponse } from 'next/server'
import { verifyReviewPayload } from '@/lib/review-token'
import { supabaseAdmin } from '@/lib/supabase-admin'
import { hmrcApiBase,hmrcGet } from '@/lib/hmrc'
import { getHmrcAccessTokenForActingCapacity } from '@/lib/hmrc-connection'
import { buildFraudHeaders } from '@/lib/hmrc-fraud'
import { hmrcAcceptHeader } from '@/lib/hmrc-api-versions'
import { normaliseHmrcErrors } from '@/lib/hmrc-errors'
import { resolveConnectedAgentForPermission } from '@/lib/agent-authorisation'
import { isSameOriginRequest } from '@/lib/request-security'
import { buildSelfEmploymentCumulativePayload,buildUkPropertyCumulativePayload,buildForeignPropertyCumulativePayload,cumulativeEndpoint,ukPropertyCumulativeEndpoint,foreignPropertyCumulativeEndpoint,taxYearFromDate } from '@/lib/hmrc-quarterly'
import { quarterlySubmissionEligibility } from '@/lib/quarterly-submission-eligibility'
import { currentWorkspace } from '@/lib/workspace'

function firstValue(obj:any,keys:string[]){for(const key of keys){const value=obj?.[key];if(value!==undefined&&value!==null&&value!=='')return value}return null}
function flattenObligations(payload:any){const groups=Array.isArray(payload?.obligations)?payload.obligations:[];return groups.flatMap((group:any)=>(group.obligationDetails||[]).map((o:any)=>({...o,businessId:group.identification||group.businessId||group.incomeSourceId||null})))}
async function foreignPropertyId(nino:string,businessId:string,taxYear:string,accessToken:string,countryCode?:string){
 const startYear=Number(String(taxYear).slice(0,4));if(!Number.isFinite(startYear)||startYear<2026)return null
 const payload=await hmrcGet(`/individuals/business/property/foreign/${encodeURIComponent(nino)}/${encodeURIComponent(businessId)}/details/${encodeURIComponent(taxYear)}`,accessToken,hmrcAcceptHeader('propertyBusiness'),'DEFAULT')
 const details=Array.isArray(payload?.foreignPropertyDetails)?payload.foreignPropertyDetails:[]
 const wanted=String(countryCode||'').trim().toUpperCase()
 const match=details.find((r:any)=>String(r?.propertyId||'')&&(wanted?String(r?.countryCode||'').toUpperCase()===wanted:true))
 return match?.propertyId?String(match.propertyId):null
}
async function reconcileAcceptedObligation(db:any,firmId:string,taxpayerId:string,nino:string,businessId:string,periodStart:string,periodEnd:string,accessToken:string){try{const startYear=Number(String(periodStart).slice(0,4));if(!Number.isFinite(startYear))return;const path=`/obligations/details/${encodeURIComponent(nino)}/income-and-expenditure?fromDate=${startYear}-04-06&toDate=${startYear+1}-04-05`;const payload=await hmrcGet(path,accessToken,hmrcAcceptHeader('obligations'),'DEFAULT');const match=flattenObligations(payload).find((o:any)=>{const end=String(firstValue(o,['periodEndDate','inboundCorrespondenceTo','end','PeriodEndDate'])||'');const source=String(o.businessId||'');return end===periodEnd&&(!source||source===businessId)});if(!match)return;const status=firstValue(match,['status','Status']);const received=firstValue(match,['receivedDate','inboundCorrespondenceDateReceived','inboundCorrespondenceReceivedDate','received','ReceivedDate']);const update:any={raw:match};if(status)update.status=status;if(received)update.received_date=received;await db.from('hmrc_obligations').update(update).eq('firm_id',firmId).eq('taxpayer_id',taxpayerId).eq('period_start',periodStart).eq('period_end',periodEnd)}catch(e:any){console.warn('Post submission obligation reconciliation deferred',e?.message||e)}}

export async function POST(req:Request){
 if(!isSameOriginRequest(req))return new NextResponse('Invalid request origin',{status:403})
 const workspace=await currentWorkspace();if(!workspace)return new NextResponse('Accounting workspace access is not available',{status:403})
 const form=await req.formData();const token=String(form.get('reviewToken')||'');const p:any=verifyReviewPayload(token);const taxpayerId=String(p?.taxpayerId||'demo');const requestedAgentId=String(form.get('actingAgentId')||'').trim()||null;const back=new URL(`/taxpayers/${encodeURIComponent(taxpayerId)}/quarterly/review`,req.url);back.searchParams.set('data',token)
 if(!p){back.searchParams.set('error','Review token is invalid or has been altered');return NextResponse.redirect(back,303)}
 if(!p.businessId){back.searchParams.set('error','Select a valid HMRC business before submission');return NextResponse.redirect(back,303)}
 if(!p.periodStart||!p.periodEnd||p.periodStart>'9999-12-31'||p.periodEnd<p.periodStart){back.searchParams.set('error','The cumulative submission period is invalid');return NextResponse.redirect(back,303)}
 if(p.periodStart<'2025-04-06'){back.searchParams.set('error','Cumulative quarterly submission requires tax year 2025/26 or later');return NextResponse.redirect(back,303)}
 if(process.env.HMRC_ENVIRONMENT==='production'&&process.env.HMRC_ALLOW_PRODUCTION_SUBMISSIONS!=='true'){back.searchParams.set('error','Production HMRC submissions are locked. Complete sandbox testing and explicitly enable production submissions first.');return NextResponse.redirect(back,303)}
 const db=supabaseAdmin();const requestedType=String(p.incomeSourceType||p.filingType||'self-employment');const [taxpayerResult,businessResult,obligationResult,submissionResult]=await Promise.all([
  db.from('taxpayers').select('nino').eq('id',taxpayerId).eq('firm_id',workspace.firmId).maybeSingle(),
  db.from('hmrc_businesses').select('business_id,business_type,raw').eq('firm_id',workspace.firmId).eq('taxpayer_id',taxpayerId).eq('business_id',p.businessId).maybeSingle(),
  db.from('hmrc_obligations').select('taxpayer_id,business_id,period_start,period_end,status').eq('firm_id',workspace.firmId).eq('taxpayer_id',taxpayerId).eq('period_start',p.periodStart).eq('period_end',p.periodEnd),
  db.from('hmrc_quarterly_submissions').select('taxpayer_id,business_id,period_start,period_end,status').eq('firm_id',workspace.firmId).eq('taxpayer_id',taxpayerId).eq('business_id',p.businessId).eq('period_start',p.periodStart).eq('period_end',p.periodEnd).in('status',['sending','submitted'])
 ]);const taxpayer=taxpayerResult.data;if(taxpayerResult.error||!taxpayer?.nino){back.searchParams.set('error','HMRC taxpayer record is missing, inaccessible, or has no NINO');return NextResponse.redirect(back,303)}
 if(businessResult.error||obligationResult.error||submissionResult.error){back.searchParams.set('error','Quarterly submission checks are temporarily unavailable');return NextResponse.redirect(back,303)}
 const eligibility=quarterlySubmissionEligibility({taxpayerId,businessId:p.businessId,periodStart:p.periodStart,periodEnd:p.periodEnd,requestedType,business:businessResult.data,obligations:obligationResult.data,submissions:submissionResult.data});if(!eligibility.ok){back.searchParams.set('error',eligibility.error);return NextResponse.redirect(back,303)}
 let actingAgentId:string|null=null;let accessToken:string;try{actingAgentId=await resolveConnectedAgentForPermission(taxpayerId,'can_submit_quarterly',requestedAgentId);accessToken=await getHmrcAccessTokenForActingCapacity(taxpayerId,actingAgentId)}catch(e:any){back.searchParams.set('error',e.message||'HMRC connection is incomplete');return NextResponse.redirect(back,303)}
 const fraud=buildFraudHeaders(req,form,taxpayerId);if(fraud.missing.length){back.searchParams.set('readiness','blocked');back.searchParams.set('missing',fraud.missing.join(','));return NextResponse.redirect(back,303)}
 const taxYear=taxYearFromDate(p.periodStart);const type=eligibility.sourceType;let requestPayload:any;let endpoint:string;let acceptHeader:string
 if(type==='foreign-property'){const propertyId=await foreignPropertyId(taxpayer.nino,p.businessId,taxYear,accessToken,p.countryCode);if(Number(taxYear.slice(0,4))>=2026&&!propertyId){back.searchParams.set('error','HMRC has no foreign property detail record for this tax year. Create or sync the foreign property detail before submitting this quarterly update.');return NextResponse.redirect(back,303)}requestPayload=buildForeignPropertyCumulativePayload({...p,propertyId},taxYear);endpoint=foreignPropertyCumulativeEndpoint(taxpayer.nino,p.businessId,taxYear);acceptHeader=hmrcAcceptHeader('propertyBusiness')}else if(type==='uk-property'){requestPayload=buildUkPropertyCumulativePayload(p);endpoint=ukPropertyCumulativeEndpoint(taxpayer.nino,p.businessId,taxYear);acceptHeader=hmrcAcceptHeader('propertyBusiness')}else{requestPayload=buildSelfEmploymentCumulativePayload(p);endpoint=cumulativeEndpoint(taxpayer.nino,p.businessId,taxYear);acceptHeader=hmrcAcceptHeader('selfEmploymentBusiness')}
 const {data:audit,error:auditError}=await db.from('hmrc_quarterly_submissions').insert({firm_id:workspace.firmId,taxpayer_id:taxpayerId,business_id:p.businessId,period_start:p.periodStart,period_end:p.periodEnd,tax_year:taxYear,status:'sending',acting_agent_id:actingAgentId,request_payload:{incomeSourceType:type,payload:requestPayload}}).select('id').maybeSingle()
 if(auditError?.code==='23505'){back.searchParams.set('error','This cumulative quarterly period has already been submitted or is currently being sent');return NextResponse.redirect(back,303)}
 if(auditError||!audit?.id){back.searchParams.set('error','Submission audit storage is not ready. Apply the Supabase quarterly submissions migration before sending anything to HMRC.');return NextResponse.redirect(back,303)}
 const auditId=audit.id
 try{const res=await fetch(`${hmrcApiBase}${endpoint}`,{method:'PUT',headers:{Authorization:`Bearer ${accessToken}`,Accept:acceptHeader,'Content-Type':'application/json',...(process.env.HMRC_ENVIRONMENT==='production'?{}:{'Gov-Test-Scenario':process.env.HMRC_TEST_SCENARIO||'DEFAULT'}),...fraud.headers},body:JSON.stringify(requestPayload),cache:'no-store'});const text=await res.text();let responsePayload:any={};try{responsePayload=text?JSON.parse(text):{}}catch{responsePayload={raw:text}};const correlationId=res.headers.get('x-correlationid')||res.headers.get('x-correlation-id');const rejections=normaliseHmrcErrors(responsePayload);await db.from('hmrc_quarterly_submissions').update({status:res.ok?'submitted':'failed',response_payload:responsePayload,hmrc_correlation_id:correlationId,hmrc_http_status:res.status,error_message:res.ok?null:(rejections[0]?.guidance||rejections[0]?.message||text||`HMRC ${res.status}`),submitted_at:res.ok?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',auditId).eq('firm_id',workspace.firmId);if(!res.ok){back.searchParams.set('submissionId',auditId);back.searchParams.set('error',rejections[0]?.guidance||rejections[0]?.message||responsePayload?.message||responsePayload?.code||`HMRC ${res.status}`);if(correlationId)back.searchParams.set('correlationId',correlationId);return NextResponse.redirect(back,303)}await reconcileAcceptedObligation(db,workspace.firmId,taxpayerId,taxpayer.nino,p.businessId,p.periodStart,p.periodEnd,accessToken);back.searchParams.set('submitted','1');back.searchParams.set('submissionId',auditId);if(actingAgentId)back.searchParams.set('actingAs','agent');if(correlationId)back.searchParams.set('correlationId',correlationId);return NextResponse.redirect(back,303)}catch(e:any){await db.from('hmrc_quarterly_submissions').update({status:'failed',error_message:e.message||'HMRC submission failed',updated_at:new Date().toISOString()}).eq('id',auditId).eq('firm_id',workspace.firmId);back.searchParams.set('submissionId',auditId);back.searchParams.set('error',e.message||'HMRC submission failed');return NextResponse.redirect(back,303)}
}