import { NextResponse } from 'next/server'
import { verifyReviewPayload } from '@/lib/review-token'
import { supabaseAdmin } from '@/lib/supabase-admin'
import { hmrcApiBase,hmrcGet } from '@/lib/hmrc'
import { getValidHmrcAccessToken } from '@/lib/hmrc-connection'
import { buildFraudHeaders } from '@/lib/hmrc-fraud'
import { hmrcAcceptHeader } from '@/lib/hmrc-api-versions'
import { agentCan } from '@/lib/agent-authorisation'
import { isSameOriginRequest } from '@/lib/request-security'
import { buildSelfEmploymentCumulativePayload,buildUkPropertyCumulativePayload,buildForeignPropertyCumulativePayload,cumulativeEndpoint,ukPropertyCumulativeEndpoint,foreignPropertyCumulativeEndpoint,taxYearFromDate } from '@/lib/hmrc-quarterly'

function rejectionDetails(payload:any){const rows:any[]=[];if(Array.isArray(payload?.errors))for(const e of payload.errors)rows.push({code:e?.code||'HMRC_ERROR',message:e?.message||'HMRC rejected this value',path:e?.path||e?.paths||''});if(!rows.length&&payload?.code)rows.push({code:payload.code,message:payload?.message||'HMRC rejected the submission',path:payload?.path||''});if(!rows.length&&payload?.message)rows.push({code:'HMRC_ERROR',message:payload.message,path:''});return rows}
function firstValue(obj:any,keys:string[]){for(const key of keys){const value=obj?.[key];if(value!==undefined&&value!==null&&value!=='')return value}return null}
function flattenObligations(payload:any){const groups=Array.isArray(payload?.obligations)?payload.obligations:[];return groups.flatMap((group:any)=>(group.obligationDetails||[]).map((o:any)=>({...o,businessId:group.identification||group.businessId||group.incomeSourceId||null})))}
async function reconcileAcceptedObligation(db:any,taxpayerId:string,nino:string,businessId:string,periodStart:string,periodEnd:string,accessToken:string){try{const startYear=Number(String(periodStart).slice(0,4));if(!Number.isFinite(startYear))return;const path=`/obligations/details/${encodeURIComponent(nino)}/income-and-expenditure?fromDate=${startYear}-04-06&toDate=${startYear+1}-04-05`;const payload=await hmrcGet(path,accessToken,hmrcAcceptHeader('obligations'),'DEFAULT');const match=flattenObligations(payload).find((o:any)=>{const end=String(firstValue(o,['periodEndDate','inboundCorrespondenceTo','end','PeriodEndDate'])||'');const source=String(o.businessId||'');return end===periodEnd&&(!source||source===businessId)});if(!match)return;const status=firstValue(match,['status','Status']);const received=firstValue(match,['receivedDate','inboundCorrespondenceDateReceived','inboundCorrespondenceReceivedDate','received','ReceivedDate']);const update:any={raw:match};if(status)update.status=status;if(received)update.received_date=received;await db.from('hmrc_obligations').update(update).eq('taxpayer_id',taxpayerId).eq('period_start',periodStart).eq('period_end',periodEnd)}catch(e:any){console.warn('Post submission obligation reconciliation deferred',e?.message||e)}}

export async function POST(req:Request){
 if(!isSameOriginRequest(req))return new NextResponse('Invalid request origin',{status:403})
 const form=await req.formData();const token=String(form.get('reviewToken')||'');const p:any=verifyReviewPayload(token);const taxpayerId=String(p?.taxpayerId||'demo');const actingAgentId=String(form.get('actingAgentId')||'').trim()||null;const back=new URL(`/taxpayers/${encodeURIComponent(taxpayerId)}/quarterly/review`,req.url);back.searchParams.set('data',token)
 if(!p){back.searchParams.set('error','Review token is invalid or has been altered');return NextResponse.redirect(back,303)}
 if(!p.businessId){back.searchParams.set('error','Select a valid HMRC business before submission');return NextResponse.redirect(back,303)}
 if(!p.periodStart||!p.periodEnd||p.periodStart>'9999-12-31'||p.periodEnd<p.periodStart){back.searchParams.set('error','The cumulative submission period is invalid');return NextResponse.redirect(back,303)}
 if(p.periodStart<'2025-04-06'){back.searchParams.set('error','Cumulative quarterly submission requires tax year 2025/26 or later');return NextResponse.redirect(back,303)}
 if(actingAgentId){const allowed=await agentCan(taxpayerId,actingAgentId,'can_submit_quarterly');if(!allowed){back.searchParams.set('error','The selected agent is not currently authorised to submit quarterly updates for this taxpayer.');return NextResponse.redirect(back,303)}}
 if(process.env.HMRC_ENVIRONMENT==='production'&&process.env.HMRC_ALLOW_PRODUCTION_SUBMISSIONS!=='true'){back.searchParams.set('error','Production HMRC submissions are locked. Complete sandbox testing and explicitly enable production submissions first.');return NextResponse.redirect(back,303)}
 const db=supabaseAdmin();const {data:taxpayer,error:taxpayerError}=await db.from('taxpayers').select('nino').eq('id',taxpayerId).maybeSingle();if(taxpayerError||!taxpayer?.nino){back.searchParams.set('error','HMRC taxpayer record is missing a NINO');return NextResponse.redirect(back,303)}
 let accessToken:string;try{accessToken=await getValidHmrcAccessToken(taxpayerId)}catch(e:any){back.searchParams.set('error',e.message||'HMRC connection is incomplete');return NextResponse.redirect(back,303)}
 const fraud=buildFraudHeaders(req,form,taxpayerId);if(fraud.missing.length){back.searchParams.set('readiness','blocked');back.searchParams.set('missing',fraud.missing.join(','));return NextResponse.redirect(back,303)}
 const taxYear=taxYearFromDate(p.periodStart);const type=String(p.incomeSourceType||p.filingType||'self-employment');let requestPayload:any;let endpoint:string;let acceptHeader:string
 if(type==='foreign-property'){requestPayload=buildForeignPropertyCumulativePayload(p);endpoint=foreignPropertyCumulativeEndpoint(taxpayer.nino,p.businessId,taxYear);acceptHeader=hmrcAcceptHeader('propertyBusiness')}else if(type==='uk-property'||type==='property'){requestPayload=buildUkPropertyCumulativePayload(p);endpoint=ukPropertyCumulativeEndpoint(taxpayer.nino,p.businessId,taxYear);acceptHeader=hmrcAcceptHeader('propertyBusiness')}else{requestPayload=buildSelfEmploymentCumulativePayload(p);endpoint=cumulativeEndpoint(taxpayer.nino,p.businessId,taxYear);acceptHeader=hmrcAcceptHeader('selfEmploymentBusiness')}
 const {data:audit,error:auditError}=await db.from('hmrc_quarterly_submissions').insert({taxpayer_id:taxpayerId,business_id:p.businessId,period_start:p.periodStart,period_end:p.periodEnd,tax_year:taxYear,status:'sending',acting_agent_id:actingAgentId,request_payload:{incomeSourceType:type,payload:requestPayload}}).select('id').maybeSingle()
 if(auditError||!audit?.id){back.searchParams.set('error','Submission audit storage is not ready. Apply the Supabase quarterly submissions migration before sending anything to HMRC.');return NextResponse.redirect(back,303)}
 const auditId=audit.id
 try{const res=await fetch(`${hmrcApiBase}${endpoint}`,{method:'PUT',headers:{Authorization:`Bearer ${accessToken}`,Accept:acceptHeader,'Content-Type':'application/json',...(process.env.HMRC_ENVIRONMENT==='production'?{}:{'Gov-Test-Scenario':process.env.HMRC_TEST_SCENARIO||'DEFAULT'}),...fraud.headers},body:JSON.stringify(requestPayload),cache:'no-store'});const text=await res.text();let responsePayload:any={};try{responsePayload=text?JSON.parse(text):{}}catch{responsePayload={raw:text}};const correlationId=res.headers.get('x-correlationid')||res.headers.get('x-correlation-id');const rejections=rejectionDetails(responsePayload);await db.from('hmrc_quarterly_submissions').update({status:res.ok?'submitted':'failed',response_payload:responsePayload,hmrc_correlation_id:correlationId,hmrc_http_status:res.status,error_message:res.ok?null:(rejections[0]?.message||text||`HMRC ${res.status}`),submitted_at:res.ok?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',auditId);if(!res.ok){if(rejections.length)back.searchParams.set('hmrcErrors',Buffer.from(JSON.stringify(rejections),'utf8').toString('base64url'));back.searchParams.set('error',rejections[0]?.message||responsePayload?.message||responsePayload?.code||`HMRC ${res.status}`);if(correlationId)back.searchParams.set('correlationId',correlationId);return NextResponse.redirect(back,303)}await reconcileAcceptedObligation(db,taxpayerId,taxpayer.nino,p.businessId,p.periodStart,p.periodEnd,accessToken);back.searchParams.set('submitted','1');if(correlationId)back.searchParams.set('correlationId',correlationId);return NextResponse.redirect(back,303)}catch(e:any){await db.from('hmrc_quarterly_submissions').update({status:'failed',error_message:e.message||'HMRC submission failed',updated_at:new Date().toISOString()}).eq('id',auditId);back.searchParams.set('error',e.message||'HMRC submission failed');return NextResponse.redirect(back,303)}
}
