import { NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase-admin'
import { hmrcApiBase } from '@/lib/hmrc'
import { getValidHmrcAccessToken } from '@/lib/hmrc-connection'
import { buildFraudHeaders } from '@/lib/hmrc-fraud'
import { isSameOriginRequest } from '@/lib/request-security'
import { currentWorkspace } from '@/lib/workspace'
import { taxYearHasEnded } from '@/lib/year-end-finalisation'

function amount(form:FormData,key:string){const raw=String(form.get(key)||'').trim();if(!raw)return undefined;const n=Number(raw);return Number.isFinite(n)?n:undefined}
function clean(obj:any):any{if(Array.isArray(obj))return obj.map(clean);if(obj&&typeof obj==='object'){const out:any={};for(const [k,v] of Object.entries(obj)){const c=clean(v);if(c!==undefined&&(typeof c!=='object'||Object.keys(c).length))out[k]=c}return out}return obj}
async function reviewed(firmId:string,taxpayerId:string,taxYear:string){await supabaseAdmin().from('mtd_year_end_reviews').upsert({firm_id:firmId,taxpayer_id:taxpayerId,tax_year:taxYear,section:'adjustments',status:'reviewed',note:'Accounting adjustments submitted successfully to HMRC.',reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'taxpayer_id,tax_year,section'})}

export async function POST(req:Request){
 if(!isSameOriginRequest(req))return new NextResponse('Invalid request origin',{status:403})
 const workspace=await currentWorkspace();if(!workspace)return new NextResponse('Accounting workspace access is not available',{status:403})
 const form=await req.formData();const taxpayerId=String(form.get('taxpayerId')||'demo');const taxYear=String(form.get('taxYear')||'');const calculationId=String(form.get('calculationId')||'').trim();const type=String(form.get('typeOfBusiness')||'self-employment');const expenseMode=String(form.get('expenseMode')||'consolidated')
 const back=new URL(`/taxpayers/${encodeURIComponent(taxpayerId)}/end-of-year/adjustments`,req.url);back.searchParams.set('taxYear',taxYear)
 if(!/^20\d{2}-\d{2}$/.test(taxYear)||!calculationId){back.searchParams.set('error','A valid tax year and BSAS calculation ID are required');return NextResponse.redirect(back,303)}
 if(!taxYearHasEnded(taxYear)){back.searchParams.set('error','Accounting adjustment submission is not available until the selected tax year has ended.');return NextResponse.redirect(back,303)}
 if(!['self-employment','uk-property'].includes(type)){back.searchParams.set('error','Unsupported business type');return NextResponse.redirect(back,303)}
 if(process.env.HMRC_ENVIRONMENT==='production'&&process.env.HMRC_ALLOW_PRODUCTION_SUBMISSIONS!=='true'){back.searchParams.set('error','Production HMRC submissions are locked until explicitly enabled.');return NextResponse.redirect(back,303)}
 const {data:taxpayer}=await supabaseAdmin().from('taxpayers').select('nino').eq('id',taxpayerId).eq('firm_id',workspace.firmId).maybeSingle();if(!taxpayer?.nino){back.searchParams.set('error','Taxpayer is not available in this accounting workspace or has no NINO');return NextResponse.redirect(back,303)}
 let token:string;try{token=await getValidHmrcAccessToken(taxpayerId)}catch(e:any){back.searchParams.set('error',e.message||'HMRC connection is incomplete');return NextResponse.redirect(back,303)}
 const fraud=buildFraudHeaders(req,form,taxpayerId);if(fraud.missing.length){back.searchParams.set('error',`Missing HMRC fraud prevention data: ${fraud.missing.join(', ')}`);return NextResponse.redirect(back,303)}
 let payload:any
 if(type==='self-employment'){
  const income={turnover:amount(form,'turnover'),other:amount(form,'otherIncome')}
  if(expenseMode==='detailed')payload=clean({income,expenses:{costOfGoods:amount(form,'costOfGoods'),paymentsToSubcontractors:amount(form,'paymentsToSubcontractors'),wagesAndStaffCosts:amount(form,'wagesAndStaffCosts'),carVanTravelExpenses:amount(form,'carVanTravelExpenses'),premisesRunningCosts:amount(form,'premisesRunningCosts'),maintenanceCosts:amount(form,'maintenanceCosts'),adminCosts:amount(form,'adminCosts'),interestOnBankOtherLoans:amount(form,'interestOnBankOtherLoans'),financeCharges:amount(form,'financeCharges'),irrecoverableDebts:amount(form,'irrecoverableDebts'),professionalFees:amount(form,'professionalFees'),depreciation:amount(form,'depreciation'),otherExpenses:amount(form,'otherExpenses'),advertisingCosts:amount(form,'advertisingCosts'),businessEntertainmentCosts:amount(form,'businessEntertainmentCosts')},additions:{costOfGoodsDisallowable:amount(form,'costOfGoodsDisallowable'),paymentsToSubcontractorsDisallowable:amount(form,'paymentsToSubcontractorsDisallowable'),wagesAndStaffCostsDisallowable:amount(form,'wagesAndStaffCostsDisallowable'),carVanTravelExpensesDisallowable:amount(form,'carVanTravelExpensesDisallowable'),premisesRunningCostsDisallowable:amount(form,'premisesRunningCostsDisallowable'),maintenanceCostsDisallowable:amount(form,'maintenanceCostsDisallowable'),adminCostsDisallowable:amount(form,'adminCostsDisallowable'),interestOnBankOtherLoansDisallowable:amount(form,'interestOnBankOtherLoansDisallowable'),financeChargesDisallowable:amount(form,'financeChargesDisallowable'),irrecoverableDebtsDisallowable:amount(form,'irrecoverableDebtsDisallowable'),professionalFeesDisallowable:amount(form,'professionalFeesDisallowable'),depreciationDisallowable:amount(form,'depreciationDisallowable'),otherExpensesDisallowable:amount(form,'otherExpensesDisallowable'),advertisingCostsDisallowable:amount(form,'advertisingCostsDisallowable'),businessEntertainmentCostsDisallowable:amount(form,'businessEntertainmentCostsDisallowable')}})
  else payload=clean({income,expenses:{consolidatedExpenses:amount(form,'consolidatedExpenses')}})
 } else payload=clean({ukProperty:{income:{totalRentsReceived:amount(form,'totalRentsReceived'),premiumsOfLeaseGrant:amount(form,'premiumsOfLeaseGrant'),reversePremiums:amount(form,'reversePremiums'),otherPropertyIncome:amount(form,'otherPropertyIncome')},expenses:{premisesRunningCosts:amount(form,'premisesRunningCosts'),repairsAndMaintenance:amount(form,'repairsAndMaintenance'),financialCosts:amount(form,'financialCosts'),professionalFees:amount(form,'professionalFees'),costOfServices:amount(form,'costOfServices'),residentialFinancialCost:amount(form,'residentialFinancialCost'),other:amount(form,'otherPropertyExpenses'),travelCosts:amount(form,'travelCosts')}}})
 if(!Object.keys(payload).length){back.searchParams.set('error','Enter at least one accounting adjustment');return NextResponse.redirect(back,303)}
 const segment=type==='self-employment'?'self-employment':'uk-property';const endpoint=`/individuals/self-assessment/adjustable-summary/${encodeURIComponent(taxpayer.nino)}/${segment}/${encodeURIComponent(calculationId)}/adjust/${encodeURIComponent(taxYear)}`
 try{const res=await fetch(`${hmrcApiBase}${endpoint}`,{method:'POST',headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.hmrc.7.0+json','Content-Type':'application/json',...(process.env.HMRC_ENVIRONMENT==='production'?{}:{'Gov-Test-Scenario':'DEFAULT'}),...fraud.headers},body:JSON.stringify(payload),cache:'no-store'});const text=await res.text();let data:any={};try{data=text?JSON.parse(text):{}}catch{data={raw:text}}const correlationId=res.headers.get('x-correlationid')||res.headers.get('x-correlation-id')||'';if(!res.ok){back.searchParams.set('error',data?.message||data?.code||`HMRC ${res.status}`);if(correlationId)back.searchParams.set('correlationId',correlationId);return NextResponse.redirect(back,303)}await reviewed(workspace.firmId,taxpayerId,taxYear);back.searchParams.set('adjustmentSubmitted','1');back.searchParams.set('calculationId',calculationId);if(correlationId)back.searchParams.set('correlationId',correlationId);return NextResponse.redirect(back,303)}catch(e:any){back.searchParams.set('error',e.message||'Could not submit HMRC accounting adjustments');return NextResponse.redirect(back,303)}
}
