import Link from 'next/link'
import TaxpayerSidebar from '@/app/components/TaxpayerSidebar'
import { supabaseAdmin } from '@/lib/supabase-admin'

export const dynamic='force-dynamic'
function decode(value?:string){try{return value?JSON.parse(Buffer.from(value,'base64url').toString('utf8')):null}catch{return null}}
function gbp(v:any){return new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(Number(v||0))}

export default async function StateBenefitsPage({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<Record<string,string|undefined>>}){
 const {id}=await params;const qs=await searchParams;const db=supabaseAdmin();const {data:obligations}=await db.from('hmrc_obligations').select('period_start').eq('taxpayer_id',id).gte('period_start','2025-04-06')
 const years=Array.from(new Set((obligations||[]).map((o:any)=>{const d=String(o.period_start);const y=Number(d.slice(0,4));return `${y}-${String(y+1).slice(-2)}`}))).sort().reverse();const selected=qs.taxYear&&years.includes(qs.taxYear)?qs.taxYear:(years[0]||'2026-27');const result:any=decode(qs.result);const rows=Array.isArray(result?.stateBenefits)?result.stateBenefits:Array.isArray(result?.benefits)?result.benefits:[]
 return <div className="shell"><TaxpayerSidebar taxpayerId={id} active="state-benefits"/><main className="main">
  <div className="top"><div><h1 className="pageTitle">State Benefits</h1><p className="muted">Review taxable state benefits held by HMRC before the end of year calculation.</p></div><span className="badge">{selected}</span></div>
  {qs.error&&<div className="status statusError"><strong>HMRC needs attention.</strong><div>{qs.error}</div>{qs.correlationId&&<div className="muted">Correlation ID: {qs.correlationId}</div>}</div>}
  <section className="panel"><div className="sectionHead"><div><h2>HMRC state benefit records</h2><p className="muted">List state benefits for the selected tax year directly from HMRC.</p></div><form method="get"><select className="selectField" name="taxYear" defaultValue={selected}>{years.length?years.map(y=><option key={y} value={y}>{y}</option>):<option value={selected}>{selected}</option>}</select><button className="btn btnSmall" type="submit">Change year</button></form></div><Link className="btn" href={`/api/hmrc/state-benefits/list?taxpayerId=${encodeURIComponent(id)}&taxYear=${encodeURIComponent(selected)}`}>Retrieve state benefits</Link></section>
  {qs.retrieved&&result&&<section className="panel" style={{marginTop:16}}><div className="sectionHead"><div><h2>HMRC benefits</h2><p className="muted">These records are held by HMRC for {selected}.</p></div>{qs.correlationId&&<span className="badge">Correlation {qs.correlationId}</span>}</div>{rows.length?<div className="tableWrap"><table><thead><tr><th>Benefit</th><th>Start</th><th>End</th><th>Amount</th><th>Tax paid</th></tr></thead><tbody>{rows.map((b:any,i:number)=><tr key={b.benefitId||i}><td>{b.benefitType||b.type||'State benefit'}</td><td>{b.startDate||'—'}</td><td>{b.endDate||'—'}</td><td>{gbp(b.amount||b.amounts?.amount)}</td><td>{gbp(b.taxPaid||b.amounts?.taxPaid)}</td></tr>)}</tbody></table></div>:<div className="status">HMRC returned a state benefits response. Expand the full response below to review its structure.</div>}<details style={{marginTop:12}}><summary>View full HMRC response</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(result,null,2)}</pre></details></section>}
  <section className="panel" style={{marginTop:16}}><h2>Year end control</h2><p className="muted">The HMRC State Benefits API also supports create, amend, delete, ignore and unignore operations. MTD Lab is keeping this first stage read only until those actions are presented with benefit specific validation and confirmation.</p><Link className="btn btnSmall" href={`/taxpayers/${id}/end-of-year?taxYear=${encodeURIComponent(selected)}`}>Back to End of Year</Link></section>
 </main></div>
}
