import { NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase-admin'
import { hmrcApiBase } from '@/lib/hmrc'
import { getValidHmrcAccessToken } from '@/lib/hmrc-connection'
import { buildFraudHeaders } from '@/lib/hmrc-fraud'
import { markYearEndReviewed } from '@/lib/year-end-review'

function num(f:FormData,k:string){const r=String(f.get(k)||'').trim();if(!r)return undefined;const v=Number(r);return Number.isFinite(v)&&v>=0?v:undefined}
function text(f:FormData,k:string){const v=String(f.get(k)||'').trim();return v||undefined}
function refAmount(f:FormData,p:string,amountKey='reliefClaimed'){const customerReference=text(f,`${p}Ref`),amount=num(f,`${p}Amount`);if(!customerReference&&amount===undefined)return undefined;if(!customerReference||amount===undefined)throw new Error(`${p} requires customer reference and amount.`);return {customerReference,[amountKey]:amount}}

export async function POST(req:Request){
 const f=await req.formData();const taxpayerId=String(f.get('taxpayerId')||'demo'),taxYear=String(f.get('taxYear')||'');const back=new URL(`/taxpayers/${encodeURIComponent(taxpayerId)}/end-of-year/reliefs`,req.url);back.searchParams.set('taxYear',taxYear);back.searchParams.set('type','other')
 try{if(!/^20\d{2}-\d{2}$/.test(taxYear))throw new Error('Select a valid HMRC tax year');const payload:any={};const ndi=refAmount(f,'nonDeductible');if(ndi)payload.nonDeductibleLoanInterest=ndi;const pg=refAmount(f,'payrollGiving');if(pg)payload.payrollGiving=pg;const qd=refAmount(f,'qualifyingDistribution','amount');if(qd)payload.qualifyingDistributionRedemptionOfSharesAndSecurities=qd;const annual=refAmount(f,'annualPayments');if(annual)payload.annualPaymentsMade=annual;
 const maintRef=text(f,'maintenanceRef'),maintName=text(f,'maintenanceName'),maintDob=text(f,'maintenanceDob'),maintAmount=num(f,'maintenanceAmount');if(maintRef||maintName||maintDob||maintAmount!==undefined){if(!maintRef||!maintName||!maintDob||maintAmount===undefined)throw new Error('Maintenance payments require reference, ex spouse name, date of birth and amount.');payload.maintenancePayments=[{customerReference:maintRef,exSpouseName:maintName,exSpouseDateOfBirth:maintDob,amount:maintAmount}]}
 const postRef=text(f,'postCessationRef'),businessName=text(f,'postCessationBusinessName'),ceased=text(f,'postCessationDate'),trade=text(f,'postCessationTrade'),incomeSource=text(f,'postCessationIncomeSource'),postAmount=num(f,'postCessationAmount');if(postRef||businessName||ceased||trade||incomeSource||postAmount!==undefined){if(!postRef||!businessName||!ceased||!trade||!incomeSource||postAmount===undefined)throw new Error('Post cessation relief requires all business details and amount.');payload.postCessationTradeReliefAndCertainOtherLosses=[{customerReference:postRef,businessName,dateBusinessCeased:ceased,natureOfTrade:trade,incomeSource,amount:postAmount}]}
 const qlRef=text(f,'qualifyingLoanRef'),lender=text(f,'qualifyingLoanLender'),qlAmount=num(f,'qualifyingLoanAmount');if(qlRef||lender||qlAmount!==undefined){if(!qlRef||!lender||qlAmount===undefined)throw new Error('Qualifying loan interest requires reference, lender name and relief claimed.');payload.qualifyingLoanInterestPayments=[{customerReference:qlRef,lenderName:lender,reliefClaimed:qlAmount}]}
 if(!Object.keys(payload).length)throw new Error('Enter at least one Other Relief item');const {data:taxpayer}=await supabaseAdmin().from('taxpayers').select('nino').eq('id',taxpayerId).maybeSingle();if(!taxpayer?.nino)throw new Error('Taxpayer NINO is missing');const token=await getValidHmrcAccessToken(taxpayerId);const fraud=buildFraudHeaders(req,f,taxpayerId);if(fraud.missing.length)throw new Error(`Missing HMRC fraud prevention data: ${fraud.missing.join(', ')}`)
 const res=await fetch(`${hmrcApiBase}/individuals/reliefs/other/${encodeURIComponent(taxpayer.nino)}/${encodeURIComponent(taxYear)}`,{method:'PUT',headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.hmrc.3.0+json','Content-Type':'application/json',...(process.env.HMRC_ENVIRONMENT==='production'?{}:{'Gov-Test-Scenario':'DEFAULT'}),...fraud.headers},body:JSON.stringify(payload),cache:'no-store'});const raw=await res.text();let data:any={};try{data=raw?JSON.parse(raw):{}}catch{data={raw}}const correlationId=res.headers.get('x-correlationid')||res.headers.get('x-correlation-id')||'';if(!res.ok){back.searchParams.set('error',data?.message||data?.code||`HMRC ${res.status}`);if(correlationId)back.searchParams.set('correlationId',correlationId);return NextResponse.redirect(back,303)}await markYearEndReviewed(taxpayerId,taxYear,'reliefs','Other reliefs updated in HMRC');back.searchParams.set('savedOther','1');if(correlationId)back.searchParams.set('correlationId',correlationId);return NextResponse.redirect(back,303)
 }catch(e:any){back.searchParams.set('error',e.message||'Could not submit Other Reliefs');return NextResponse.redirect(back,303)}
}
