import Link from 'next/link'
import { supabaseAdmin } from '@/lib/supabase-admin'
import { HMRC_API_VERSIONS } from '@/lib/hmrc-api-versions'
import { expireAgentAuthorisations } from '@/lib/agent-authorisation'
import { assessHmrcConnection } from '@/lib/hmrc-connection-status'
import { incomeSourceTypeFromBusinessId, type MtdIncomeSourceType } from '@/lib/mtd-income-source'

export const dynamic='force-dynamic'
const laneOrder:MtdIncomeSourceType[]=['self-employment','uk-property','foreign-property']
function label(type:MtdIncomeSourceType){return type==='uk-property'?'UK Property':type==='foreign-property'?'Foreign Property':'Self Assessment'}
function submissionType(row:any):MtdIncomeSourceType{const raw=JSON.stringify(row.request_payload||{}).toLowerCase();if(raw.includes('foreignproperty'))return 'foreign-property';if(raw.includes('ukproperty'))return 'uk-property';return incomeSourceTypeFromBusinessId(row.business_id)}
function taxYearEnded(taxYear:string){const start=Number(taxYear.slice(0,4));return Number.isFinite(start)&&Date.now()>=Date.UTC(start+1,3,6)}

export default async function ReleaseReadinessPage(){
 const db=supabaseAdmin();try{await expireAgentAuthorisations()}catch{}
 const [connections,syncs,quarterly,obligations,calculations,finals,directFinals,agentFinals,loginAttempts,digitalRecords,yearEndReviews,evidenceBucket]=await Promise.all([
  db.from('hmrc_connections').select('access_token,refresh_token,token_expires_at,scope'),
  db.from('hmrc_sync_runs').select('id',{count:'exact',head:true}).eq('status','complete'),
  db.from('hmrc_quarterly_submissions').select('business_id,request_payload,acting_agent_id,status').eq('status','submitted'),
  db.from('hmrc_obligations').select('business_id,period_start').gte('period_start','2025-04-06').not('business_id','is',null),
  db.from('mtd_submission_audit').select('id,tax_year,calculation_id,hmrc_correlation_id',{count:'exact'}).eq('event_type','tax_calculation_retrieval').eq('status','accepted'),
  db.from('mtd_submission_audit').select('id',{count:'exact',head:true}).eq('event_type','final_declaration').eq('status','accepted'),
  db.from('mtd_submission_audit').select('id',{count:'exact',head:true}).eq('event_type','final_declaration').eq('status','accepted').is('acting_agent_id',null),
  db.from('mtd_submission_audit').select('id',{count:'exact',head:true}).eq('event_type','final_declaration').eq('status','accepted').not('acting_agent_id','is',null),
  db.from('app_login_attempts').select('id',{count:'exact',head:true}),
  db.from('mtd_digital_records').select('id',{count:'exact',head:true}),
  db.from('mtd_year_end_reviews').select('id',{count:'exact',head:true}).in('status',['reviewed','not_applicable']),
  db.storage.getBucket('mtd-evidence')
 ])
 const accepted=quarterly.data||[];const directQuarterly=accepted.filter((row:any)=>!row.acting_agent_id).length;const agentQuarterly=accepted.filter((row:any)=>row.acting_agent_id).length;const applicableBusinessIds=Array.from(new Set((obligations.data||[]).map((row:any)=>String(row.business_id||'')).filter(Boolean)));const acceptedBusinessIds=new Set(accepted.map((row:any)=>String(row.business_id||'')));const applicableTypes=new Set(applicableBusinessIds.map(incomeSourceTypeFromBusinessId));const laneEvidence=laneOrder.map(type=>{const count=accepted.filter((row:any)=>submissionType(row)===type).length;const applicable=applicableTypes.has(type);return {type,label:label(type),applicable,count,ok:!applicable||count>0}})
 const calculationRows=calculations.data||[];const calculationTaxYears=Array.from(new Set(calculationRows.map((row:any)=>String(row.tax_year||'')).filter(Boolean))).sort();const latestCalculationTaxYear=calculationTaxYears[calculationTaxYears.length-1]||'';const finalDeclarationNotDue=Boolean(latestCalculationTaxYear&&!taxYearEnded(latestCalculationTaxYear));const finalDeclarationAccepted=(finals.count||0)>0;const finalDeclarationOk=finalDeclarationAccepted||finalDeclarationNotDue;const finalDeclarationDetail=finalDeclarationAccepted?`${finals.count||0} accepted Final Declaration(s). Direct ${directFinals.count||0}, agent ${agentFinals.count||0}.`:finalDeclarationNotDue?`${latestCalculationTaxYear} has not ended yet. Final Declaration is correctly blocked until after the tax year ends.`:`0 accepted Final Declaration(s). Direct ${directFinals.count||0}, agent ${agentFinals.count||0}.`
 const connectionStatuses=(connections.data||[]).map(c=>assessHmrcConnection(c));const usableConnections=connectionStatuses.filter(c=>c.usable).length;const reconnectRequired=connectionStatuses.filter(c=>c.connected&&!c.usable).length;const env=process.env.HMRC_ENVIRONMENT||'sandbox';const productionEnabled=process.env.HMRC_ALLOW_PRODUCTION_SUBMISSIONS==='true';const configReady=Boolean(process.env.HMRC_CLIENT_ID&&process.env.HMRC_CLIENT_SECRET&&process.env.HMRC_REDIRECT_URI&&process.env.HMRC_STATE_SECRET&&process.env.SUPABASE_SERVICE_ROLE_KEY);const allApplicableBusinessesTested=applicableBusinessIds.length>0&&applicableBusinessIds.every(id=>acceptedBusinessIds.has(id))
 const evidenceChecks=[
  {name:'Core HMRC and Supabase secrets configured',ok:configReady,detail:configReady?'Required server configuration is present.':'One or more required server environment variables are missing.'},
  {name:'Usable HMRC connection evidence',ok:usableConnections>0,detail:`${usableConnections} usable HMRC connection(s). ${reconnectRequired} require reconnect.`},
  {name:'Successful HMRC synchronisation',ok:(syncs.count||0)>0,detail:`${syncs.count||0} successful synchronisation run(s).`},
  {name:'Every applicable income-source lane tested',ok:laneEvidence.every(item=>item.ok),detail:laneEvidence.map(item=>`${item.label}: ${item.applicable?item.count+' accepted':'not applicable'}`).join(' · ')},
  {name:'Every applicable HMRC business ID tested',ok:allApplicableBusinessesTested,detail:`${acceptedBusinessIds.size} of ${applicableBusinessIds.length} applicable income source ID(s) have accepted quarterly evidence.`},
  {name:'Direct quarterly filing tested',ok:directQuarterly>0,detail:`${directQuarterly} accepted direct quarterly update(s).`},
  {name:'Agent delegated quarterly filing tested',ok:agentQuarterly>0,detail:`${agentQuarterly} accepted delegated quarterly update(s).`},
  {name:'Digital-record storage and audit available',ok:!digitalRecords.error&&!evidenceBucket.error,detail:evidenceBucket.error?'Private supporting-document bucket is unavailable.':`Private evidence storage is ready. ${digitalRecords.count||0} digital record(s) stored.`},
  {name:'Controlled year-end reviews recorded',ok:(yearEndReviews.count||0)>0,detail:`${yearEndReviews.count||0} reviewed or not-applicable year-end section(s).`},
  {name:'HMRC calculation retrieval evidence',ok:(calculations.count||0)>0,detail:`${calculations.count||0} accepted calculation retrieval(s).${latestCalculationTaxYear?` Latest tax year ${latestCalculationTaxYear}.`:''}`},
  {name:'Final Declaration timing and evidence',ok:finalDeclarationOk,detail:finalDeclarationDetail},
  {name:'Login abuse audit storage',ok:!loginAttempts.error,detail:loginAttempts.error?'Login attempt audit table is unavailable.':'Login attempt audit and rate limit storage is available.'},
  {name:'Central HMRC API version registry',ok:Boolean(HMRC_API_VERSIONS),detail:'HMRC API media type versions are centrally controlled.'}
 ]
 const safetyLock={name:'Production submission safety lock',ok:env!=='production'||!productionEnabled,detail:env==='production'?(productionEnabled?'Production submissions are enabled. Confirm explicit release approval and monitoring.':'Production environment detected, submission lock remains active.'):'Sandbox environment active. Production submissions remain isolated.'};const preReleaseReady=evidenceChecks.every(check=>check.ok)&&safetyLock.ok;const productionLive=preReleaseReady&&env==='production'&&productionEnabled;const checks=[...evidenceChecks,safetyLock];const passed=checks.filter(check=>check.ok).length;const stateLabel=productionLive?'Production enabled':preReleaseReady?'Pre release ready':'Validation incomplete'
 return <div className="shell"><aside className="side"><div className="brand">MTD Lab</div><div className="nav"><Link href="/">Dashboard</Link><Link href="/taxpayers">Taxpayers</Link><Link href="/agents">Agents</Link><Link href="/taxpayers/sandbox">Sandbox setup</Link><span>Release readiness</span></div><div className="operator">Operated by Glomaxel IT Service</div></aside><main className="main"><div className="top"><div><h1 className="pageTitle">Stage 2 release readiness</h1><p className="muted">Controlled evidence gate before any production MTD Income Tax submission capability is enabled.</p></div><span className={`statusPill ${preReleaseReady?'statusDone':'statusOpen'}`}>{stateLabel}</span></div><div className="cards" style={{marginTop:20}}><div className="card"><span className="eyebrow">Checks passed</span><strong>{passed} of {checks.length}</strong></div><div className="card"><span className="eyebrow">HMRC environment</span><strong>{env}</strong></div><div className="card"><span className="eyebrow">Production submissions</span><strong>{productionEnabled?'Enabled':'Locked'}</strong></div><div className="card"><span className="eyebrow">Applicable sources</span><strong>{applicableBusinessIds.length}</strong></div></div><section className="panel" style={{marginTop:16}}><h2>Income-source sandbox evidence</h2><div className="tableWrap"><table><thead><tr><th>Lane</th><th>Applicable</th><th>Accepted submissions</th><th>Status</th></tr></thead><tbody>{laneEvidence.map(item=><tr key={item.type}><td><strong>{item.label}</strong></td><td>{item.applicable?'Yes':'No'}</td><td>{item.count}</td><td><span className={`statusPill ${item.ok?'statusDone':'statusOpen'}`}>{item.ok?'Pass':'Pending'}</span></td></tr>)}</tbody></table></div></section><section className="panel" style={{marginTop:16}}><h2>Release gate</h2><div className="tableWrap"><table><thead><tr><th>Control</th><th>Status</th><th>Evidence</th></tr></thead><tbody>{checks.map(check=><tr key={check.name}><td><strong>{check.name}</strong></td><td><span className={`statusPill ${check.ok?'statusDone':'statusOpen'}`}>{check.ok?'Pass':'Pending'}</span></td><td>{check.detail}</td></tr>)}</tbody></table></div></section><div className="status" style={{marginTop:16}}><strong>Safety rule:</strong> Pre-release readiness must be achieved while production submissions remain locked. Production activation remains a separate explicit action after HMRC approval and final review.</div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:16}}><Link className="btn" href="/taxpayers/sandbox">Open sandbox validation</Link><Link className="btn btnSmall" href="/agents">Review agents</Link><a className="btn btnSmall" href="/api/hmrc/version-health" target="_blank" rel="noreferrer">API version health</a></div></main></div>
}
